// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/nstehr/vimy/vimy-core/baml_client/stream_types"
	"github.com/nstehr/vimy/vimy-core/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.Resume":        reflect.TypeOf(types.Resume{}),
	"STREAM_TYPES.Resume": reflect.TypeOf(stream_types.Resume{}),
}
