// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type BlockedClauseClassView struct {
	inner baml.ClassBuilder
}

func (t *BlockedClauseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *BlockedClauseClassView) PropertySource() (ClassPropertyView, error) {
	return t.inner.Property("source")
}

func (t *BlockedClauseClassView) PropertyFile() (ClassPropertyView, error) {
	return t.inner.Property("file")
}

func (t *BlockedClauseClassView) PropertyLine() (ClassPropertyView, error) {
	return t.inner.Property("line")
}

func (t *BlockedClauseClassView) PropertySole() (ClassPropertyView, error) {
	return t.inner.Property("sole")
}

func (t *BlockedClauseClassView) PropertySole_rate() (ClassPropertyView, error) {
	return t.inner.Property("sole_rate")
}

func (t *BlockedClauseClassView) PropertyBlocked() (ClassPropertyView, error) {
	return t.inner.Property("blocked")
}

func (t *BlockedClauseClassView) PropertyRules() (ClassPropertyView, error) {
	return t.inner.Property("rules")
}

func (t *BlockedClauseClassView) PropertyWorking() (ClassPropertyView, error) {
	return t.inner.Property("working")
}

func (t *TypeBuilder) BlockedClause() (*BlockedClauseClassView, error) {
	bld, err := t.inner.Class("BlockedClause")
	if err != nil {
		return nil, err
	}
	return &BlockedClauseClassView{inner: bld}, nil
}

func (t *BlockedClauseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ClauseSensitivityClassView struct {
	inner baml.ClassBuilder
}

func (t *ClauseSensitivityClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ClauseSensitivityClassView) PropertySource() (ClassPropertyView, error) {
	return t.inner.Property("source")
}

func (t *ClauseSensitivityClassView) PropertyFile() (ClassPropertyView, error) {
	return t.inner.Property("file")
}

func (t *ClauseSensitivityClassView) PropertyLine() (ClassPropertyView, error) {
	return t.inner.Property("line")
}

func (t *ClauseSensitivityClassView) PropertyRules() (ClassPropertyView, error) {
	return t.inner.Property("rules")
}

func (t *ClauseSensitivityClassView) PropertyWindows() (ClassPropertyView, error) {
	return t.inner.Property("windows")
}

func (t *ClauseSensitivityClassView) PropertyLow_rate() (ClassPropertyView, error) {
	return t.inner.Property("low_rate")
}

func (t *ClauseSensitivityClassView) PropertyHigh_rate() (ClassPropertyView, error) {
	return t.inner.Property("high_rate")
}

func (t *ClauseSensitivityClassView) PropertyDoctrinal() (ClassPropertyView, error) {
	return t.inner.Property("doctrinal")
}

func (t *ClauseSensitivityClassView) PropertyKnob() (ClassPropertyView, error) {
	return t.inner.Property("knob")
}

func (t *ClauseSensitivityClassView) PropertyKnob_low() (ClassPropertyView, error) {
	return t.inner.Property("knob_low")
}

func (t *ClauseSensitivityClassView) PropertyKnob_high() (ClassPropertyView, error) {
	return t.inner.Property("knob_high")
}

func (t *ClauseSensitivityClassView) PropertyRate_low() (ClassPropertyView, error) {
	return t.inner.Property("rate_low")
}

func (t *ClauseSensitivityClassView) PropertyRate_high() (ClassPropertyView, error) {
	return t.inner.Property("rate_high")
}

func (t *ClauseSensitivityClassView) PropertyVerdict() (ClassPropertyView, error) {
	return t.inner.Property("verdict")
}

func (t *TypeBuilder) ClauseSensitivity() (*ClauseSensitivityClassView, error) {
	bld, err := t.inner.Class("ClauseSensitivity")
	if err != nil {
		return nil, err
	}
	return &ClauseSensitivityClassView{inner: bld}, nil
}

func (t *ClauseSensitivityClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DeadRuleClassView struct {
	inner baml.ClassBuilder
}

func (t *DeadRuleClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DeadRuleClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *DeadRuleClassView) PropertyCategory() (ClassPropertyView, error) {
	return t.inner.Property("category")
}

func (t *DeadRuleClassView) PropertyMatched() (ClassPropertyView, error) {
	return t.inner.Property("matched")
}

func (t *DeadRuleClassView) PropertyActed() (ClassPropertyView, error) {
	return t.inner.Property("acted")
}

func (t *DeadRuleClassView) PropertySeen() (ClassPropertyView, error) {
	return t.inner.Property("seen")
}

func (t *DeadRuleClassView) PropertyCulprit() (ClassPropertyView, error) {
	return t.inner.Property("culprit")
}

func (t *DeadRuleClassView) PropertyCulprit_sole() (ClassPropertyView, error) {
	return t.inner.Property("culprit_sole")
}

func (t *TypeBuilder) DeadRule() (*DeadRuleClassView, error) {
	bld, err := t.inner.Class("DeadRule")
	if err != nil {
		return nil, err
	}
	return &DeadRuleClassView{inner: bld}, nil
}

func (t *DeadRuleClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DirectiveAdviceClassView struct {
	inner baml.ClassBuilder
}

func (t *DirectiveAdviceClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DirectiveAdviceClassView) PropertyDiagnosis() (ClassPropertyView, error) {
	return t.inner.Property("diagnosis")
}

func (t *DirectiveAdviceClassView) PropertyRevision() (ClassPropertyView, error) {
	return t.inner.Property("revision")
}

func (t *DirectiveAdviceClassView) PropertyConfidence() (ClassPropertyView, error) {
	return t.inner.Property("confidence")
}

func (t *TypeBuilder) DirectiveAdvice() (*DirectiveAdviceClassView, error) {
	bld, err := t.inner.Class("DirectiveAdvice")
	if err != nil {
		return nil, err
	}
	return &DirectiveAdviceClassView{inner: bld}, nil
}

func (t *DirectiveAdviceClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DoctrineChoiceClassView struct {
	inner baml.ClassBuilder
}

func (t *DoctrineChoiceClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DoctrineChoiceClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *DoctrineChoiceClassView) PropertyRationale() (ClassPropertyView, error) {
	return t.inner.Property("rationale")
}

func (t *DoctrineChoiceClassView) PropertyInfantry_weight() (ClassPropertyView, error) {
	return t.inner.Property("infantry_weight")
}

func (t *DoctrineChoiceClassView) PropertyVehicle_weight() (ClassPropertyView, error) {
	return t.inner.Property("vehicle_weight")
}

func (t *DoctrineChoiceClassView) PropertyAir_weight() (ClassPropertyView, error) {
	return t.inner.Property("air_weight")
}

func (t *DoctrineChoiceClassView) PropertyTech_priority() (ClassPropertyView, error) {
	return t.inner.Property("tech_priority")
}

func (t *DoctrineChoiceClassView) PropertyEconomy_priority() (ClassPropertyView, error) {
	return t.inner.Property("economy_priority")
}

func (t *DoctrineChoiceClassView) PropertyAggression() (ClassPropertyView, error) {
	return t.inner.Property("aggression")
}

func (t *TypeBuilder) DoctrineChoice() (*DoctrineChoiceClassView, error) {
	bld, err := t.inner.Class("DoctrineChoice")
	if err != nil {
		return nil, err
	}
	return &DoctrineChoiceClassView{inner: bld}, nil
}

func (t *DoctrineChoiceClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type FindingClassView struct {
	inner baml.ClassBuilder
}

func (t *FindingClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *FindingClassView) PropertyClaim() (ClassPropertyView, error) {
	return t.inner.Property("claim")
}

func (t *FindingClassView) PropertyEvidence() (ClassPropertyView, error) {
	return t.inner.Property("evidence")
}

func (t *FindingClassView) PropertyConfidence() (ClassPropertyView, error) {
	return t.inner.Property("confidence")
}

func (t *TypeBuilder) Finding() (*FindingClassView, error) {
	bld, err := t.inner.Class("Finding")
	if err != nil {
		return nil, err
	}
	return &FindingClassView{inner: bld}, nil
}

func (t *FindingClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GameFactsClassView struct {
	inner baml.ClassBuilder
}

func (t *GameFactsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GameFactsClassView) PropertyOur_faction() (ClassPropertyView, error) {
	return t.inner.Property("our_faction")
}

func (t *GameFactsClassView) PropertyOpponent_faction() (ClassPropertyView, error) {
	return t.inner.Property("opponent_faction")
}

func (t *GameFactsClassView) PropertyOutcome() (ClassPropertyView, error) {
	return t.inner.Property("outcome")
}

func (t *GameFactsClassView) PropertyDuration_ticks() (ClassPropertyView, error) {
	return t.inner.Property("duration_ticks")
}

func (t *GameFactsClassView) PropertyDoctrine_windows() (ClassPropertyView, error) {
	return t.inner.Property("doctrine_windows")
}

func (t *GameFactsClassView) PropertyStates_replayed() (ClassPropertyView, error) {
	return t.inner.Property("states_replayed")
}

func (t *GameFactsClassView) PropertyRules_in_set() (ClassPropertyView, error) {
	return t.inner.Property("rules_in_set")
}

func (t *GameFactsClassView) PropertyNever_fired() (ClassPropertyView, error) {
	return t.inner.Property("never_fired")
}

func (t *GameFactsClassView) PropertyNo_single_cause() (ClassPropertyView, error) {
	return t.inner.Property("no_single_cause")
}

func (t *GameFactsClassView) PropertyTop_clauses() (ClassPropertyView, error) {
	return t.inner.Property("top_clauses")
}

func (t *GameFactsClassView) PropertyDead_rules() (ClassPropertyView, error) {
	return t.inner.Property("dead_rules")
}

func (t *GameFactsClassView) PropertyDoctrine_names() (ClassPropertyView, error) {
	return t.inner.Property("doctrine_names")
}

func (t *GameFactsClassView) PropertySensitivity() (ClassPropertyView, error) {
	return t.inner.Property("sensitivity")
}

func (t *GameFactsClassView) PropertyGates() (ClassPropertyView, error) {
	return t.inner.Property("gates")
}

func (t *GameFactsClassView) PropertyFaction() (ClassPropertyView, error) {
	return t.inner.Property("faction")
}

func (t *GameFactsClassView) PropertyDirective() (ClassPropertyView, error) {
	return t.inner.Property("directive")
}

func (t *GameFactsClassView) PropertyDoctrines() (ClassPropertyView, error) {
	return t.inner.Property("doctrines")
}

func (t *GameFactsClassView) PropertyMissing() (ClassPropertyView, error) {
	return t.inner.Property("missing")
}

func (t *TypeBuilder) GameFacts() (*GameFactsClassView, error) {
	bld, err := t.inner.Class("GameFacts")
	if err != nil {
		return nil, err
	}
	return &GameFactsClassView{inner: bld}, nil
}

func (t *GameFactsClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type InsightClassView struct {
	inner baml.ClassBuilder
}

func (t *InsightClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *InsightClassView) PropertySummary() (ClassPropertyView, error) {
	return t.inner.Property("summary")
}

func (t *InsightClassView) PropertyFindings() (ClassPropertyView, error) {
	return t.inner.Property("findings")
}

func (t *InsightClassView) PropertySuggestion() (ClassPropertyView, error) {
	return t.inner.Property("suggestion")
}

func (t *InsightClassView) PropertyCaveat() (ClassPropertyView, error) {
	return t.inner.Property("caveat")
}

func (t *InsightClassView) PropertyDirective_advice() (ClassPropertyView, error) {
	return t.inner.Property("directive_advice")
}

func (t *TypeBuilder) Insight() (*InsightClassView, error) {
	bld, err := t.inner.Class("Insight")
	if err != nil {
		return nil, err
	}
	return &InsightClassView{inner: bld}, nil
}

func (t *InsightClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MissingThingClassView struct {
	inner baml.ClassBuilder
}

func (t *MissingThingClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MissingThingClassView) PropertyRule() (ClassPropertyView, error) {
	return t.inner.Property("rule")
}

func (t *MissingThingClassView) PropertyClause() (ClassPropertyView, error) {
	return t.inner.Property("clause")
}

func (t *MissingThingClassView) PropertyThing() (ClassPropertyView, error) {
	return t.inner.Property("thing")
}

func (t *MissingThingClassView) PropertyMaker() (ClassPropertyView, error) {
	return t.inner.Property("maker")
}

func (t *MissingThingClassView) PropertyMaker_matched() (ClassPropertyView, error) {
	return t.inner.Property("maker_matched")
}

func (t *MissingThingClassView) PropertyMaker_culprit() (ClassPropertyView, error) {
	return t.inner.Property("maker_culprit")
}

func (t *MissingThingClassView) PropertyVerdict() (ClassPropertyView, error) {
	return t.inner.Property("verdict")
}

func (t *TypeBuilder) MissingThing() (*MissingThingClassView, error) {
	bld, err := t.inner.Class("MissingThing")
	if err != nil {
		return nil, err
	}
	return &MissingThingClassView{inner: bld}, nil
}

func (t *MissingThingClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TunableGateClassView struct {
	inner baml.ClassBuilder
}

func (t *TunableGateClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TunableGateClassView) PropertySource() (ClassPropertyView, error) {
	return t.inner.Property("source")
}

func (t *TunableGateClassView) PropertyFile() (ClassPropertyView, error) {
	return t.inner.Property("file")
}

func (t *TunableGateClassView) PropertyLine() (ClassPropertyView, error) {
	return t.inner.Property("line")
}

func (t *TunableGateClassView) PropertyRules() (ClassPropertyView, error) {
	return t.inner.Property("rules")
}

func (t *TunableGateClassView) PropertyAt() (ClassPropertyView, error) {
	return t.inner.Property("at")
}

func (t *TunableGateClassView) PropertyBlocked() (ClassPropertyView, error) {
	return t.inner.Property("blocked")
}

func (t *TunableGateClassView) PropertyRelief() (ClassPropertyView, error) {
	return t.inner.Property("relief")
}

func (t *TunableGateClassView) PropertyRelief_at() (ClassPropertyView, error) {
	return t.inner.Property("relief_at")
}

func (t *TunableGateClassView) PropertyReached() (ClassPropertyView, error) {
	return t.inner.Property("reached")
}

func (t *TypeBuilder) TunableGate() (*TunableGateClassView, error) {
	bld, err := t.inner.Class("TunableGate")
	if err != nil {
		return nil, err
	}
	return &TunableGateClassView{inner: bld}, nil
}

func (t *TunableGateClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
