// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type BlockedClause struct {
	Source    string   `json:"source"`
	File      string   `json:"file"`
	Line      int64    `json:"line"`
	Sole      int64    `json:"sole"`
	Sole_rate float64  `json:"sole_rate"`
	Blocked   int64    `json:"blocked"`
	Rules     []string `json:"rules"`
	Working   int64    `json:"working"`
}

func (c *BlockedClause) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "BlockedClause" {
		panic(fmt.Sprintf("expected BlockedClause, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "source":
			c.Source = baml.Decode(valueHolder).Interface().(string)

		case "file":
			c.File = baml.Decode(valueHolder).Interface().(string)

		case "line":
			c.Line = baml.Decode(valueHolder).Int()

		case "sole":
			c.Sole = baml.Decode(valueHolder).Int()

		case "sole_rate":
			c.Sole_rate = baml.Decode(valueHolder).Float()

		case "blocked":
			c.Blocked = baml.Decode(valueHolder).Int()

		case "rules":
			c.Rules = baml.Decode(valueHolder).Interface().([]string)

		case "working":
			c.Working = baml.Decode(valueHolder).Int()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class BlockedClause", key))

		}
	}

}

func (c BlockedClause) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["source"] = c.Source

	fields["file"] = c.File

	fields["line"] = c.Line

	fields["sole"] = c.Sole

	fields["sole_rate"] = c.Sole_rate

	fields["blocked"] = c.Blocked

	fields["rules"] = c.Rules

	fields["working"] = c.Working

	return baml.EncodeClass("BlockedClause", fields, nil)
}

func (c BlockedClause) BamlTypeName() string {
	return "BlockedClause"
}

type ClauseSensitivity struct {
	Source    string  `json:"source"`
	File      string  `json:"file"`
	Line      int64   `json:"line"`
	Rules     int64   `json:"rules"`
	Windows   int64   `json:"windows"`
	Low_rate  float64 `json:"low_rate"`
	High_rate float64 `json:"high_rate"`
	Doctrinal bool    `json:"doctrinal"`
	Knob      string  `json:"knob"`
	Knob_low  float64 `json:"knob_low"`
	Knob_high float64 `json:"knob_high"`
	Rate_low  float64 `json:"rate_low"`
	Rate_high float64 `json:"rate_high"`
	Verdict   string  `json:"verdict"`
}

func (c *ClauseSensitivity) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ClauseSensitivity" {
		panic(fmt.Sprintf("expected ClauseSensitivity, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "source":
			c.Source = baml.Decode(valueHolder).Interface().(string)

		case "file":
			c.File = baml.Decode(valueHolder).Interface().(string)

		case "line":
			c.Line = baml.Decode(valueHolder).Int()

		case "rules":
			c.Rules = baml.Decode(valueHolder).Int()

		case "windows":
			c.Windows = baml.Decode(valueHolder).Int()

		case "low_rate":
			c.Low_rate = baml.Decode(valueHolder).Float()

		case "high_rate":
			c.High_rate = baml.Decode(valueHolder).Float()

		case "doctrinal":
			c.Doctrinal = baml.Decode(valueHolder).Bool()

		case "knob":
			c.Knob = baml.Decode(valueHolder).Interface().(string)

		case "knob_low":
			c.Knob_low = baml.Decode(valueHolder).Float()

		case "knob_high":
			c.Knob_high = baml.Decode(valueHolder).Float()

		case "rate_low":
			c.Rate_low = baml.Decode(valueHolder).Float()

		case "rate_high":
			c.Rate_high = baml.Decode(valueHolder).Float()

		case "verdict":
			c.Verdict = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ClauseSensitivity", key))

		}
	}

}

func (c ClauseSensitivity) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["source"] = c.Source

	fields["file"] = c.File

	fields["line"] = c.Line

	fields["rules"] = c.Rules

	fields["windows"] = c.Windows

	fields["low_rate"] = c.Low_rate

	fields["high_rate"] = c.High_rate

	fields["doctrinal"] = c.Doctrinal

	fields["knob"] = c.Knob

	fields["knob_low"] = c.Knob_low

	fields["knob_high"] = c.Knob_high

	fields["rate_low"] = c.Rate_low

	fields["rate_high"] = c.Rate_high

	fields["verdict"] = c.Verdict

	return baml.EncodeClass("ClauseSensitivity", fields, nil)
}

func (c ClauseSensitivity) BamlTypeName() string {
	return "ClauseSensitivity"
}

type DeadRule struct {
	Name         string `json:"name"`
	Category     string `json:"category"`
	Matched      int64  `json:"matched"`
	Acted        int64  `json:"acted"`
	Seen         int64  `json:"seen"`
	Culprit      string `json:"culprit"`
	Culprit_sole int64  `json:"culprit_sole"`
}

func (c *DeadRule) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "DeadRule" {
		panic(fmt.Sprintf("expected DeadRule, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(string)

		case "category":
			c.Category = baml.Decode(valueHolder).Interface().(string)

		case "matched":
			c.Matched = baml.Decode(valueHolder).Int()

		case "acted":
			c.Acted = baml.Decode(valueHolder).Int()

		case "seen":
			c.Seen = baml.Decode(valueHolder).Int()

		case "culprit":
			c.Culprit = baml.Decode(valueHolder).Interface().(string)

		case "culprit_sole":
			c.Culprit_sole = baml.Decode(valueHolder).Int()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class DeadRule", key))

		}
	}

}

func (c DeadRule) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["category"] = c.Category

	fields["matched"] = c.Matched

	fields["acted"] = c.Acted

	fields["seen"] = c.Seen

	fields["culprit"] = c.Culprit

	fields["culprit_sole"] = c.Culprit_sole

	return baml.EncodeClass("DeadRule", fields, nil)
}

func (c DeadRule) BamlTypeName() string {
	return "DeadRule"
}

type DirectiveAdvice struct {
	Diagnosis  string  `json:"diagnosis"`
	Revision   string  `json:"revision"`
	Confidence float64 `json:"confidence"`
}

func (c *DirectiveAdvice) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "DirectiveAdvice" {
		panic(fmt.Sprintf("expected DirectiveAdvice, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "diagnosis":
			c.Diagnosis = baml.Decode(valueHolder).Interface().(string)

		case "revision":
			c.Revision = baml.Decode(valueHolder).Interface().(string)

		case "confidence":
			c.Confidence = baml.Decode(valueHolder).Float()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class DirectiveAdvice", key))

		}
	}

}

func (c DirectiveAdvice) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["diagnosis"] = c.Diagnosis

	fields["revision"] = c.Revision

	fields["confidence"] = c.Confidence

	return baml.EncodeClass("DirectiveAdvice", fields, nil)
}

func (c DirectiveAdvice) BamlTypeName() string {
	return "DirectiveAdvice"
}

type DoctrineChoice struct {
	Name             string  `json:"name"`
	Rationale        string  `json:"rationale"`
	Infantry_weight  float64 `json:"infantry_weight"`
	Vehicle_weight   float64 `json:"vehicle_weight"`
	Air_weight       float64 `json:"air_weight"`
	Tech_priority    float64 `json:"tech_priority"`
	Economy_priority float64 `json:"economy_priority"`
	Aggression       float64 `json:"aggression"`
}

func (c *DoctrineChoice) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "DoctrineChoice" {
		panic(fmt.Sprintf("expected DoctrineChoice, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(string)

		case "rationale":
			c.Rationale = baml.Decode(valueHolder).Interface().(string)

		case "infantry_weight":
			c.Infantry_weight = baml.Decode(valueHolder).Float()

		case "vehicle_weight":
			c.Vehicle_weight = baml.Decode(valueHolder).Float()

		case "air_weight":
			c.Air_weight = baml.Decode(valueHolder).Float()

		case "tech_priority":
			c.Tech_priority = baml.Decode(valueHolder).Float()

		case "economy_priority":
			c.Economy_priority = baml.Decode(valueHolder).Float()

		case "aggression":
			c.Aggression = baml.Decode(valueHolder).Float()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class DoctrineChoice", key))

		}
	}

}

func (c DoctrineChoice) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["rationale"] = c.Rationale

	fields["infantry_weight"] = c.Infantry_weight

	fields["vehicle_weight"] = c.Vehicle_weight

	fields["air_weight"] = c.Air_weight

	fields["tech_priority"] = c.Tech_priority

	fields["economy_priority"] = c.Economy_priority

	fields["aggression"] = c.Aggression

	return baml.EncodeClass("DoctrineChoice", fields, nil)
}

func (c DoctrineChoice) BamlTypeName() string {
	return "DoctrineChoice"
}

type Finding struct {
	Claim      string  `json:"claim"`
	Evidence   string  `json:"evidence"`
	Confidence float64 `json:"confidence"`
}

func (c *Finding) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Finding" {
		panic(fmt.Sprintf("expected Finding, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "claim":
			c.Claim = baml.Decode(valueHolder).Interface().(string)

		case "evidence":
			c.Evidence = baml.Decode(valueHolder).Interface().(string)

		case "confidence":
			c.Confidence = baml.Decode(valueHolder).Float()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Finding", key))

		}
	}

}

func (c Finding) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["claim"] = c.Claim

	fields["evidence"] = c.Evidence

	fields["confidence"] = c.Confidence

	return baml.EncodeClass("Finding", fields, nil)
}

func (c Finding) BamlTypeName() string {
	return "Finding"
}

type GameFacts struct {
	Our_faction      string              `json:"our_faction"`
	Opponent_faction string              `json:"opponent_faction"`
	Outcome          string              `json:"outcome"`
	Duration_ticks   int64               `json:"duration_ticks"`
	Doctrine_windows int64               `json:"doctrine_windows"`
	States_replayed  int64               `json:"states_replayed"`
	Rules_in_set     int64               `json:"rules_in_set"`
	Never_fired      int64               `json:"never_fired"`
	No_single_cause  int64               `json:"no_single_cause"`
	Top_clauses      []BlockedClause     `json:"top_clauses"`
	Dead_rules       []DeadRule          `json:"dead_rules"`
	Doctrine_names   []string            `json:"doctrine_names"`
	Sensitivity      []ClauseSensitivity `json:"sensitivity"`
	Gates            []TunableGate       `json:"gates"`
	Faction          string              `json:"faction"`
	Directive        string              `json:"directive"`
	Doctrines        []DoctrineChoice    `json:"doctrines"`
	Missing          []MissingThing      `json:"missing"`
}

func (c *GameFacts) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GameFacts" {
		panic(fmt.Sprintf("expected GameFacts, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "our_faction":
			c.Our_faction = baml.Decode(valueHolder).Interface().(string)

		case "opponent_faction":
			c.Opponent_faction = baml.Decode(valueHolder).Interface().(string)

		case "outcome":
			c.Outcome = baml.Decode(valueHolder).Interface().(string)

		case "duration_ticks":
			c.Duration_ticks = baml.Decode(valueHolder).Int()

		case "doctrine_windows":
			c.Doctrine_windows = baml.Decode(valueHolder).Int()

		case "states_replayed":
			c.States_replayed = baml.Decode(valueHolder).Int()

		case "rules_in_set":
			c.Rules_in_set = baml.Decode(valueHolder).Int()

		case "never_fired":
			c.Never_fired = baml.Decode(valueHolder).Int()

		case "no_single_cause":
			c.No_single_cause = baml.Decode(valueHolder).Int()

		case "top_clauses":
			c.Top_clauses = baml.Decode(valueHolder).Interface().([]BlockedClause)

		case "dead_rules":
			c.Dead_rules = baml.Decode(valueHolder).Interface().([]DeadRule)

		case "doctrine_names":
			c.Doctrine_names = baml.Decode(valueHolder).Interface().([]string)

		case "sensitivity":
			c.Sensitivity = baml.Decode(valueHolder).Interface().([]ClauseSensitivity)

		case "gates":
			c.Gates = baml.Decode(valueHolder).Interface().([]TunableGate)

		case "faction":
			c.Faction = baml.Decode(valueHolder).Interface().(string)

		case "directive":
			c.Directive = baml.Decode(valueHolder).Interface().(string)

		case "doctrines":
			c.Doctrines = baml.Decode(valueHolder).Interface().([]DoctrineChoice)

		case "missing":
			c.Missing = baml.Decode(valueHolder).Interface().([]MissingThing)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GameFacts", key))

		}
	}

}

func (c GameFacts) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["our_faction"] = c.Our_faction

	fields["opponent_faction"] = c.Opponent_faction

	fields["outcome"] = c.Outcome

	fields["duration_ticks"] = c.Duration_ticks

	fields["doctrine_windows"] = c.Doctrine_windows

	fields["states_replayed"] = c.States_replayed

	fields["rules_in_set"] = c.Rules_in_set

	fields["never_fired"] = c.Never_fired

	fields["no_single_cause"] = c.No_single_cause

	fields["top_clauses"] = c.Top_clauses

	fields["dead_rules"] = c.Dead_rules

	fields["doctrine_names"] = c.Doctrine_names

	fields["sensitivity"] = c.Sensitivity

	fields["gates"] = c.Gates

	fields["faction"] = c.Faction

	fields["directive"] = c.Directive

	fields["doctrines"] = c.Doctrines

	fields["missing"] = c.Missing

	return baml.EncodeClass("GameFacts", fields, nil)
}

func (c GameFacts) BamlTypeName() string {
	return "GameFacts"
}

type Insight struct {
	Summary          string           `json:"summary"`
	Findings         []Finding        `json:"findings"`
	Suggestion       string           `json:"suggestion"`
	Caveat           string           `json:"caveat"`
	Directive_advice *DirectiveAdvice `json:"directive_advice"`
}

func (c *Insight) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Insight" {
		panic(fmt.Sprintf("expected Insight, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "summary":
			c.Summary = baml.Decode(valueHolder).Interface().(string)

		case "findings":
			c.Findings = baml.Decode(valueHolder).Interface().([]Finding)

		case "suggestion":
			c.Suggestion = baml.Decode(valueHolder).Interface().(string)

		case "caveat":
			c.Caveat = baml.Decode(valueHolder).Interface().(string)

		case "directive_advice":
			c.Directive_advice = baml.Decode(valueHolder).Interface().(*DirectiveAdvice)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Insight", key))

		}
	}

}

func (c Insight) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["summary"] = c.Summary

	fields["findings"] = c.Findings

	fields["suggestion"] = c.Suggestion

	fields["caveat"] = c.Caveat

	fields["directive_advice"] = c.Directive_advice

	return baml.EncodeClass("Insight", fields, nil)
}

func (c Insight) BamlTypeName() string {
	return "Insight"
}

type MissingThing struct {
	Rule          string `json:"rule"`
	Clause        string `json:"clause"`
	Thing         string `json:"thing"`
	Maker         string `json:"maker"`
	Maker_matched int64  `json:"maker_matched"`
	Maker_culprit string `json:"maker_culprit"`
	Verdict       string `json:"verdict"`
}

func (c *MissingThing) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "MissingThing" {
		panic(fmt.Sprintf("expected MissingThing, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "rule":
			c.Rule = baml.Decode(valueHolder).Interface().(string)

		case "clause":
			c.Clause = baml.Decode(valueHolder).Interface().(string)

		case "thing":
			c.Thing = baml.Decode(valueHolder).Interface().(string)

		case "maker":
			c.Maker = baml.Decode(valueHolder).Interface().(string)

		case "maker_matched":
			c.Maker_matched = baml.Decode(valueHolder).Int()

		case "maker_culprit":
			c.Maker_culprit = baml.Decode(valueHolder).Interface().(string)

		case "verdict":
			c.Verdict = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class MissingThing", key))

		}
	}

}

func (c MissingThing) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["rule"] = c.Rule

	fields["clause"] = c.Clause

	fields["thing"] = c.Thing

	fields["maker"] = c.Maker

	fields["maker_matched"] = c.Maker_matched

	fields["maker_culprit"] = c.Maker_culprit

	fields["verdict"] = c.Verdict

	return baml.EncodeClass("MissingThing", fields, nil)
}

func (c MissingThing) BamlTypeName() string {
	return "MissingThing"
}

type TunableGate struct {
	Source    string  `json:"source"`
	File      string  `json:"file"`
	Line      int64   `json:"line"`
	Rules     int64   `json:"rules"`
	At        float64 `json:"at"`
	Blocked   int64   `json:"blocked"`
	Relief    int64   `json:"relief"`
	Relief_at float64 `json:"relief_at"`
	Reached   float64 `json:"reached"`
}

func (c *TunableGate) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "TunableGate" {
		panic(fmt.Sprintf("expected TunableGate, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "source":
			c.Source = baml.Decode(valueHolder).Interface().(string)

		case "file":
			c.File = baml.Decode(valueHolder).Interface().(string)

		case "line":
			c.Line = baml.Decode(valueHolder).Int()

		case "rules":
			c.Rules = baml.Decode(valueHolder).Int()

		case "at":
			c.At = baml.Decode(valueHolder).Float()

		case "blocked":
			c.Blocked = baml.Decode(valueHolder).Int()

		case "relief":
			c.Relief = baml.Decode(valueHolder).Int()

		case "relief_at":
			c.Relief_at = baml.Decode(valueHolder).Float()

		case "reached":
			c.Reached = baml.Decode(valueHolder).Float()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class TunableGate", key))

		}
	}

}

func (c TunableGate) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["source"] = c.Source

	fields["file"] = c.File

	fields["line"] = c.Line

	fields["rules"] = c.Rules

	fields["at"] = c.At

	fields["blocked"] = c.Blocked

	fields["relief"] = c.Relief

	fields["relief_at"] = c.Relief_at

	fields["reached"] = c.Reached

	return baml.EncodeClass("TunableGate", fields, nil)
}

func (c TunableGate) BamlTypeName() string {
	return "TunableGate"
}
