// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type ActiveProduction struct {
	Queue    string `json:"queue"`
	Item     string `json:"item"`
	Progress int64  `json:"progress"`
}

func (c *ActiveProduction) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ActiveProduction" {
		panic(fmt.Sprintf("expected ActiveProduction, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "queue":
			c.Queue = baml.Decode(valueHolder).Interface().(string)

		case "item":
			c.Item = baml.Decode(valueHolder).Interface().(string)

		case "progress":
			c.Progress = baml.Decode(valueHolder).Int()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ActiveProduction", key))

		}
	}

}

func (c ActiveProduction) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["queue"] = c.Queue

	fields["item"] = c.Item

	fields["progress"] = c.Progress

	return baml.EncodeClass("ActiveProduction", fields, nil)
}

func (c ActiveProduction) BamlTypeName() string {
	return "ActiveProduction"
}

type CandidateCautionary struct {
	Id             int64  `json:"id"`
	Context        string `json:"context"`
	Failed_pattern string `json:"failed_pattern"`
	Failure_reason string `json:"failure_reason"`
}

func (c *CandidateCautionary) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "CandidateCautionary" {
		panic(fmt.Sprintf("expected CandidateCautionary, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "id":
			c.Id = baml.Decode(valueHolder).Int()

		case "context":
			c.Context = baml.Decode(valueHolder).Interface().(string)

		case "failed_pattern":
			c.Failed_pattern = baml.Decode(valueHolder).Interface().(string)

		case "failure_reason":
			c.Failure_reason = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class CandidateCautionary", key))

		}
	}

}

func (c CandidateCautionary) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["id"] = c.Id

	fields["context"] = c.Context

	fields["failed_pattern"] = c.Failed_pattern

	fields["failure_reason"] = c.Failure_reason

	return baml.EncodeClass("CandidateCautionary", fields, nil)
}

func (c CandidateCautionary) BamlTypeName() string {
	return "CandidateCautionary"
}

type CandidateExemplar struct {
	Id               int64  `json:"id"`
	Context          string `json:"context"`
	Rationale        string `json:"rationale"`
	Doctrine_summary string `json:"doctrine_summary"`
}

func (c *CandidateExemplar) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "CandidateExemplar" {
		panic(fmt.Sprintf("expected CandidateExemplar, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "id":
			c.Id = baml.Decode(valueHolder).Int()

		case "context":
			c.Context = baml.Decode(valueHolder).Interface().(string)

		case "rationale":
			c.Rationale = baml.Decode(valueHolder).Interface().(string)

		case "doctrine_summary":
			c.Doctrine_summary = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class CandidateExemplar", key))

		}
	}

}

func (c CandidateExemplar) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["id"] = c.Id

	fields["context"] = c.Context

	fields["rationale"] = c.Rationale

	fields["doctrine_summary"] = c.Doctrine_summary

	return baml.EncodeClass("CandidateExemplar", fields, nil)
}

func (c CandidateExemplar) BamlTypeName() string {
	return "CandidateExemplar"
}

type CandidateLesson struct {
	Id         int64   `json:"id"`
	Trigger    string  `json:"trigger"`
	Guidance   string  `json:"guidance"`
	Confidence float64 `json:"confidence"`
}

func (c *CandidateLesson) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "CandidateLesson" {
		panic(fmt.Sprintf("expected CandidateLesson, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "id":
			c.Id = baml.Decode(valueHolder).Int()

		case "trigger":
			c.Trigger = baml.Decode(valueHolder).Interface().(string)

		case "guidance":
			c.Guidance = baml.Decode(valueHolder).Interface().(string)

		case "confidence":
			c.Confidence = baml.Decode(valueHolder).Float()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class CandidateLesson", key))

		}
	}

}

func (c CandidateLesson) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["id"] = c.Id

	fields["trigger"] = c.Trigger

	fields["guidance"] = c.Guidance

	fields["confidence"] = c.Confidence

	return baml.EncodeClass("CandidateLesson", fields, nil)
}

func (c CandidateLesson) BamlTypeName() string {
	return "CandidateLesson"
}

type CautionaryPattern struct {
	Context        string `json:"context"`
	Failed_pattern string `json:"failed_pattern"`
	Failure_reason string `json:"failure_reason"`
}

func (c *CautionaryPattern) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "CautionaryPattern" {
		panic(fmt.Sprintf("expected CautionaryPattern, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "context":
			c.Context = baml.Decode(valueHolder).Interface().(string)

		case "failed_pattern":
			c.Failed_pattern = baml.Decode(valueHolder).Interface().(string)

		case "failure_reason":
			c.Failure_reason = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class CautionaryPattern", key))

		}
	}

}

func (c CautionaryPattern) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["context"] = c.Context

	fields["failed_pattern"] = c.Failed_pattern

	fields["failure_reason"] = c.Failure_reason

	return baml.EncodeClass("CautionaryPattern", fields, nil)
}

func (c CautionaryPattern) BamlTypeName() string {
	return "CautionaryPattern"
}

type CombatStats struct {
	Infantry_lost int64 `json:"infantry_lost"`
	Vehicles_lost int64 `json:"vehicles_lost"`
	Aircraft_lost int64 `json:"aircraft_lost"`
	Naval_lost    int64 `json:"naval_lost"`
}

func (c *CombatStats) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "CombatStats" {
		panic(fmt.Sprintf("expected CombatStats, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "infantry_lost":
			c.Infantry_lost = baml.Decode(valueHolder).Int()

		case "vehicles_lost":
			c.Vehicles_lost = baml.Decode(valueHolder).Int()

		case "aircraft_lost":
			c.Aircraft_lost = baml.Decode(valueHolder).Int()

		case "naval_lost":
			c.Naval_lost = baml.Decode(valueHolder).Int()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class CombatStats", key))

		}
	}

}

func (c CombatStats) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["infantry_lost"] = c.Infantry_lost

	fields["vehicles_lost"] = c.Vehicles_lost

	fields["aircraft_lost"] = c.Aircraft_lost

	fields["naval_lost"] = c.Naval_lost

	return baml.EncodeClass("CombatStats", fields, nil)
}

func (c CombatStats) BamlTypeName() string {
	return "CombatStats"
}

type Doctrine struct {
	Name                           string   `json:"name"`
	Rationale                      string   `json:"rationale"`
	Economy_priority               float64  `json:"economy_priority"`
	Aggression                     float64  `json:"aggression"`
	Ground_defense_priority        float64  `json:"ground_defense_priority"`
	Air_defense_priority           float64  `json:"air_defense_priority"`
	Tech_priority                  float64  `json:"tech_priority"`
	Infantry_weight                float64  `json:"infantry_weight"`
	Vehicle_weight                 float64  `json:"vehicle_weight"`
	Air_weight                     float64  `json:"air_weight"`
	Naval_weight                   float64  `json:"naval_weight"`
	Ground_attack_group_size       int64    `json:"ground_attack_group_size"`
	Air_attack_group_size          int64    `json:"air_attack_group_size"`
	Naval_attack_group_size        int64    `json:"naval_attack_group_size"`
	Scout_priority                 float64  `json:"scout_priority"`
	Specialized_infantry_weight    float64  `json:"specialized_infantry_weight"`
	Superweapon_priority           float64  `json:"superweapon_priority"`
	Capture_priority               float64  `json:"capture_priority"`
	Transport_assault              float64  `json:"transport_assault"`
	Preferred_infantry             []string `json:"preferred_infantry"`
	Preferred_vehicle              []string `json:"preferred_vehicle"`
	Preferred_aircraft             []string `json:"preferred_aircraft"`
	Preferred_naval                []string `json:"preferred_naval"`
	Ground_target_aa_priority      float64  `json:"ground_target_aa_priority"`
	Air_target_ground_def_priority float64  `json:"air_target_ground_def_priority"`
	Commit_ratio                   float64  `json:"commit_ratio"`
	Base_defense_floor             int64    `json:"base_defense_floor"`
	Repair_budget_ratio            float64  `json:"repair_budget_ratio"`
	Scout_reach_priority           float64  `json:"scout_reach_priority"`
}

func (c *Doctrine) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Doctrine" {
		panic(fmt.Sprintf("expected Doctrine, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(string)

		case "rationale":
			c.Rationale = baml.Decode(valueHolder).Interface().(string)

		case "economy_priority":
			c.Economy_priority = baml.Decode(valueHolder).Float()

		case "aggression":
			c.Aggression = baml.Decode(valueHolder).Float()

		case "ground_defense_priority":
			c.Ground_defense_priority = baml.Decode(valueHolder).Float()

		case "air_defense_priority":
			c.Air_defense_priority = baml.Decode(valueHolder).Float()

		case "tech_priority":
			c.Tech_priority = baml.Decode(valueHolder).Float()

		case "infantry_weight":
			c.Infantry_weight = baml.Decode(valueHolder).Float()

		case "vehicle_weight":
			c.Vehicle_weight = baml.Decode(valueHolder).Float()

		case "air_weight":
			c.Air_weight = baml.Decode(valueHolder).Float()

		case "naval_weight":
			c.Naval_weight = baml.Decode(valueHolder).Float()

		case "ground_attack_group_size":
			c.Ground_attack_group_size = baml.Decode(valueHolder).Int()

		case "air_attack_group_size":
			c.Air_attack_group_size = baml.Decode(valueHolder).Int()

		case "naval_attack_group_size":
			c.Naval_attack_group_size = baml.Decode(valueHolder).Int()

		case "scout_priority":
			c.Scout_priority = baml.Decode(valueHolder).Float()

		case "specialized_infantry_weight":
			c.Specialized_infantry_weight = baml.Decode(valueHolder).Float()

		case "superweapon_priority":
			c.Superweapon_priority = baml.Decode(valueHolder).Float()

		case "capture_priority":
			c.Capture_priority = baml.Decode(valueHolder).Float()

		case "transport_assault":
			c.Transport_assault = baml.Decode(valueHolder).Float()

		case "preferred_infantry":
			c.Preferred_infantry = baml.Decode(valueHolder).Interface().([]string)

		case "preferred_vehicle":
			c.Preferred_vehicle = baml.Decode(valueHolder).Interface().([]string)

		case "preferred_aircraft":
			c.Preferred_aircraft = baml.Decode(valueHolder).Interface().([]string)

		case "preferred_naval":
			c.Preferred_naval = baml.Decode(valueHolder).Interface().([]string)

		case "ground_target_aa_priority":
			c.Ground_target_aa_priority = baml.Decode(valueHolder).Float()

		case "air_target_ground_def_priority":
			c.Air_target_ground_def_priority = baml.Decode(valueHolder).Float()

		case "commit_ratio":
			c.Commit_ratio = baml.Decode(valueHolder).Float()

		case "base_defense_floor":
			c.Base_defense_floor = baml.Decode(valueHolder).Int()

		case "repair_budget_ratio":
			c.Repair_budget_ratio = baml.Decode(valueHolder).Float()

		case "scout_reach_priority":
			c.Scout_reach_priority = baml.Decode(valueHolder).Float()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Doctrine", key))

		}
	}

}

func (c Doctrine) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["rationale"] = c.Rationale

	fields["economy_priority"] = c.Economy_priority

	fields["aggression"] = c.Aggression

	fields["ground_defense_priority"] = c.Ground_defense_priority

	fields["air_defense_priority"] = c.Air_defense_priority

	fields["tech_priority"] = c.Tech_priority

	fields["infantry_weight"] = c.Infantry_weight

	fields["vehicle_weight"] = c.Vehicle_weight

	fields["air_weight"] = c.Air_weight

	fields["naval_weight"] = c.Naval_weight

	fields["ground_attack_group_size"] = c.Ground_attack_group_size

	fields["air_attack_group_size"] = c.Air_attack_group_size

	fields["naval_attack_group_size"] = c.Naval_attack_group_size

	fields["scout_priority"] = c.Scout_priority

	fields["specialized_infantry_weight"] = c.Specialized_infantry_weight

	fields["superweapon_priority"] = c.Superweapon_priority

	fields["capture_priority"] = c.Capture_priority

	fields["transport_assault"] = c.Transport_assault

	fields["preferred_infantry"] = c.Preferred_infantry

	fields["preferred_vehicle"] = c.Preferred_vehicle

	fields["preferred_aircraft"] = c.Preferred_aircraft

	fields["preferred_naval"] = c.Preferred_naval

	fields["ground_target_aa_priority"] = c.Ground_target_aa_priority

	fields["air_target_ground_def_priority"] = c.Air_target_ground_def_priority

	fields["commit_ratio"] = c.Commit_ratio

	fields["base_defense_floor"] = c.Base_defense_floor

	fields["repair_budget_ratio"] = c.Repair_budget_ratio

	fields["scout_reach_priority"] = c.Scout_reach_priority

	return baml.EncodeClass("Doctrine", fields, nil)
}

func (c Doctrine) BamlTypeName() string {
	return "Doctrine"
}

type DoctrineHistoryEntry struct {
	Tick     int64    `json:"tick"`
	Doctrine Doctrine `json:"doctrine"`
}

func (c *DoctrineHistoryEntry) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "DoctrineHistoryEntry" {
		panic(fmt.Sprintf("expected DoctrineHistoryEntry, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "tick":
			c.Tick = baml.Decode(valueHolder).Int()

		case "doctrine":
			c.Doctrine = baml.Decode(valueHolder).Interface().(Doctrine)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class DoctrineHistoryEntry", key))

		}
	}

}

func (c DoctrineHistoryEntry) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["tick"] = c.Tick

	fields["doctrine"] = c.Doctrine

	return baml.EncodeClass("DoctrineHistoryEntry", fields, nil)
}

func (c DoctrineHistoryEntry) BamlTypeName() string {
	return "DoctrineHistoryEntry"
}

type DoctrineRating struct {
	Name      string `json:"name"`
	Rating    string `json:"rating"`
	Reasoning string `json:"reasoning"`
}

func (c *DoctrineRating) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "DoctrineRating" {
		panic(fmt.Sprintf("expected DoctrineRating, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(string)

		case "rating":
			c.Rating = baml.Decode(valueHolder).Interface().(string)

		case "reasoning":
			c.Reasoning = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class DoctrineRating", key))

		}
	}

}

func (c DoctrineRating) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["rating"] = c.Rating

	fields["reasoning"] = c.Reasoning

	return baml.EncodeClass("DoctrineRating", fields, nil)
}

func (c DoctrineRating) BamlTypeName() string {
	return "DoctrineRating"
}

type EnemyBase struct {
	Owner          string `json:"owner"`
	X              int64  `json:"x"`
	Y              int64  `json:"y"`
	Last_seen_tick int64  `json:"last_seen_tick"`
}

func (c *EnemyBase) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "EnemyBase" {
		panic(fmt.Sprintf("expected EnemyBase, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "owner":
			c.Owner = baml.Decode(valueHolder).Interface().(string)

		case "x":
			c.X = baml.Decode(valueHolder).Int()

		case "y":
			c.Y = baml.Decode(valueHolder).Int()

		case "last_seen_tick":
			c.Last_seen_tick = baml.Decode(valueHolder).Int()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class EnemyBase", key))

		}
	}

}

func (c EnemyBase) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["owner"] = c.Owner

	fields["x"] = c.X

	fields["y"] = c.Y

	fields["last_seen_tick"] = c.Last_seen_tick

	return baml.EncodeClass("EnemyBase", fields, nil)
}

func (c EnemyBase) BamlTypeName() string {
	return "EnemyBase"
}

type GameEvent struct {
	Kind   string `json:"kind"`
	Tick   int64  `json:"tick"`
	Detail string `json:"detail"`
}

func (c *GameEvent) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GameEvent" {
		panic(fmt.Sprintf("expected GameEvent, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "kind":
			c.Kind = baml.Decode(valueHolder).Interface().(string)

		case "tick":
			c.Tick = baml.Decode(valueHolder).Int()

		case "detail":
			c.Detail = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GameEvent", key))

		}
	}

}

func (c GameEvent) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["kind"] = c.Kind

	fields["tick"] = c.Tick

	fields["detail"] = c.Detail

	return baml.EncodeClass("GameEvent", fields, nil)
}

func (c GameEvent) BamlTypeName() string {
	return "GameEvent"
}

type GameReview struct {
	Summary          string           `json:"summary"`
	Quality_tag      string           `json:"quality_tag"`
	Turning_points   []TurningPoint   `json:"turning_points"`
	Doctrine_ratings []DoctrineRating `json:"doctrine_ratings"`
	Lessons          []RetroLesson    `json:"lessons"`
}

func (c *GameReview) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GameReview" {
		panic(fmt.Sprintf("expected GameReview, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "summary":
			c.Summary = baml.Decode(valueHolder).Interface().(string)

		case "quality_tag":
			c.Quality_tag = baml.Decode(valueHolder).Interface().(string)

		case "turning_points":
			c.Turning_points = baml.Decode(valueHolder).Interface().([]TurningPoint)

		case "doctrine_ratings":
			c.Doctrine_ratings = baml.Decode(valueHolder).Interface().([]DoctrineRating)

		case "lessons":
			c.Lessons = baml.Decode(valueHolder).Interface().([]RetroLesson)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GameReview", key))

		}
	}

}

func (c GameReview) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["summary"] = c.Summary

	fields["quality_tag"] = c.Quality_tag

	fields["turning_points"] = c.Turning_points

	fields["doctrine_ratings"] = c.Doctrine_ratings

	fields["lessons"] = c.Lessons

	return baml.EncodeClass("GameReview", fields, nil)
}

func (c GameReview) BamlTypeName() string {
	return "GameReview"
}

type GameSituation struct {
	Tick                         int64                `json:"tick"`
	Phase                        string               `json:"phase"`
	Cash                         int64                `json:"cash"`
	Resources                    int64                `json:"resources"`
	Resource_capacity            int64                `json:"resource_capacity"`
	Power                        PowerStatus          `json:"power"`
	Buildings                    []TypeCount          `json:"buildings"`
	Units                        []TypeCount          `json:"units"`
	Idle_unit_count              int64                `json:"idle_unit_count"`
	Active_production            []ActiveProduction   `json:"active_production"`
	Support_powers               []SupportPowerStatus `json:"support_powers"`
	Superweapon_fires            []SuperweaponFire    `json:"superweapon_fires"`
	Squads                       []SquadInfo          `json:"squads"`
	Enemies_visible              int64                `json:"enemies_visible"`
	Enemy_units                  []TypeCount          `json:"enemy_units"`
	Enemy_units_seen             []TypeCount          `json:"enemy_units_seen"`
	Enemy_buildings              []TypeCount          `json:"enemy_buildings"`
	Enemy_buildings_seen         []TypeCount          `json:"enemy_buildings_seen"`
	Known_enemy_bases            []EnemyBase          `json:"known_enemy_bases"`
	Map_width                    int64                `json:"map_width"`
	Map_height                   int64                `json:"map_height"`
	Recent_events                []GameEvent          `json:"recent_events"`
	Combat_stats                 *CombatStats         `json:"combat_stats"`
	Recent_doctrines             []RecentDoctrine     `json:"recent_doctrines"`
	Burned_axes                  []string             `json:"burned_axes"`
	Capturables_visible          []TypeCount          `json:"capturables_visible"`
	Being_rushed                 bool                 `json:"being_rushed"`
	Harvester_harassed           bool                 `json:"harvester_harassed"`
	Ground_squad_ready_ratio     float64              `json:"ground_squad_ready_ratio"`
	Cash_burn_rate               int64                `json:"cash_burn_rate"`
	Faction_side                 string               `json:"faction_side"`
	Unbuildable_roles            []string             `json:"unbuildable_roles"`
	Harvester_share              float64              `json:"harvester_share"`
	Our_combat_units             int64                `json:"our_combat_units"`
	Enemy_combat_units_seen      int64                `json:"enemy_combat_units_seen"`
	Time_to_reach_enemy_estimate int64                `json:"time_to_reach_enemy_estimate"`
}

func (c *GameSituation) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GameSituation" {
		panic(fmt.Sprintf("expected GameSituation, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "tick":
			c.Tick = baml.Decode(valueHolder).Int()

		case "phase":
			c.Phase = baml.Decode(valueHolder).Interface().(string)

		case "cash":
			c.Cash = baml.Decode(valueHolder).Int()

		case "resources":
			c.Resources = baml.Decode(valueHolder).Int()

		case "resource_capacity":
			c.Resource_capacity = baml.Decode(valueHolder).Int()

		case "power":
			c.Power = baml.Decode(valueHolder).Interface().(PowerStatus)

		case "buildings":
			c.Buildings = baml.Decode(valueHolder).Interface().([]TypeCount)

		case "units":
			c.Units = baml.Decode(valueHolder).Interface().([]TypeCount)

		case "idle_unit_count":
			c.Idle_unit_count = baml.Decode(valueHolder).Int()

		case "active_production":
			c.Active_production = baml.Decode(valueHolder).Interface().([]ActiveProduction)

		case "support_powers":
			c.Support_powers = baml.Decode(valueHolder).Interface().([]SupportPowerStatus)

		case "superweapon_fires":
			c.Superweapon_fires = baml.Decode(valueHolder).Interface().([]SuperweaponFire)

		case "squads":
			c.Squads = baml.Decode(valueHolder).Interface().([]SquadInfo)

		case "enemies_visible":
			c.Enemies_visible = baml.Decode(valueHolder).Int()

		case "enemy_units":
			c.Enemy_units = baml.Decode(valueHolder).Interface().([]TypeCount)

		case "enemy_units_seen":
			c.Enemy_units_seen = baml.Decode(valueHolder).Interface().([]TypeCount)

		case "enemy_buildings":
			c.Enemy_buildings = baml.Decode(valueHolder).Interface().([]TypeCount)

		case "enemy_buildings_seen":
			c.Enemy_buildings_seen = baml.Decode(valueHolder).Interface().([]TypeCount)

		case "known_enemy_bases":
			c.Known_enemy_bases = baml.Decode(valueHolder).Interface().([]EnemyBase)

		case "map_width":
			c.Map_width = baml.Decode(valueHolder).Int()

		case "map_height":
			c.Map_height = baml.Decode(valueHolder).Int()

		case "recent_events":
			c.Recent_events = baml.Decode(valueHolder).Interface().([]GameEvent)

		case "combat_stats":
			c.Combat_stats = baml.Decode(valueHolder).Interface().(*CombatStats)

		case "recent_doctrines":
			c.Recent_doctrines = baml.Decode(valueHolder).Interface().([]RecentDoctrine)

		case "burned_axes":
			c.Burned_axes = baml.Decode(valueHolder).Interface().([]string)

		case "capturables_visible":
			c.Capturables_visible = baml.Decode(valueHolder).Interface().([]TypeCount)

		case "being_rushed":
			c.Being_rushed = baml.Decode(valueHolder).Bool()

		case "harvester_harassed":
			c.Harvester_harassed = baml.Decode(valueHolder).Bool()

		case "ground_squad_ready_ratio":
			c.Ground_squad_ready_ratio = baml.Decode(valueHolder).Float()

		case "cash_burn_rate":
			c.Cash_burn_rate = baml.Decode(valueHolder).Int()

		case "faction_side":
			c.Faction_side = baml.Decode(valueHolder).Interface().(string)

		case "unbuildable_roles":
			c.Unbuildable_roles = baml.Decode(valueHolder).Interface().([]string)

		case "harvester_share":
			c.Harvester_share = baml.Decode(valueHolder).Float()

		case "our_combat_units":
			c.Our_combat_units = baml.Decode(valueHolder).Int()

		case "enemy_combat_units_seen":
			c.Enemy_combat_units_seen = baml.Decode(valueHolder).Int()

		case "time_to_reach_enemy_estimate":
			c.Time_to_reach_enemy_estimate = baml.Decode(valueHolder).Int()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GameSituation", key))

		}
	}

}

func (c GameSituation) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["tick"] = c.Tick

	fields["phase"] = c.Phase

	fields["cash"] = c.Cash

	fields["resources"] = c.Resources

	fields["resource_capacity"] = c.Resource_capacity

	fields["power"] = c.Power

	fields["buildings"] = c.Buildings

	fields["units"] = c.Units

	fields["idle_unit_count"] = c.Idle_unit_count

	fields["active_production"] = c.Active_production

	fields["support_powers"] = c.Support_powers

	fields["superweapon_fires"] = c.Superweapon_fires

	fields["squads"] = c.Squads

	fields["enemies_visible"] = c.Enemies_visible

	fields["enemy_units"] = c.Enemy_units

	fields["enemy_units_seen"] = c.Enemy_units_seen

	fields["enemy_buildings"] = c.Enemy_buildings

	fields["enemy_buildings_seen"] = c.Enemy_buildings_seen

	fields["known_enemy_bases"] = c.Known_enemy_bases

	fields["map_width"] = c.Map_width

	fields["map_height"] = c.Map_height

	fields["recent_events"] = c.Recent_events

	fields["combat_stats"] = c.Combat_stats

	fields["recent_doctrines"] = c.Recent_doctrines

	fields["burned_axes"] = c.Burned_axes

	fields["capturables_visible"] = c.Capturables_visible

	fields["being_rushed"] = c.Being_rushed

	fields["harvester_harassed"] = c.Harvester_harassed

	fields["ground_squad_ready_ratio"] = c.Ground_squad_ready_ratio

	fields["cash_burn_rate"] = c.Cash_burn_rate

	fields["faction_side"] = c.Faction_side

	fields["unbuildable_roles"] = c.Unbuildable_roles

	fields["harvester_share"] = c.Harvester_share

	fields["our_combat_units"] = c.Our_combat_units

	fields["enemy_combat_units_seen"] = c.Enemy_combat_units_seen

	fields["time_to_reach_enemy_estimate"] = c.Time_to_reach_enemy_estimate

	return baml.EncodeClass("GameSituation", fields, nil)
}

func (c GameSituation) BamlTypeName() string {
	return "GameSituation"
}

type MemoryCandidates struct {
	Exemplars    []CandidateExemplar   `json:"exemplars"`
	Cautionaries []CandidateCautionary `json:"cautionaries"`
	Lessons      []CandidateLesson     `json:"lessons"`
}

func (c *MemoryCandidates) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "MemoryCandidates" {
		panic(fmt.Sprintf("expected MemoryCandidates, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "exemplars":
			c.Exemplars = baml.Decode(valueHolder).Interface().([]CandidateExemplar)

		case "cautionaries":
			c.Cautionaries = baml.Decode(valueHolder).Interface().([]CandidateCautionary)

		case "lessons":
			c.Lessons = baml.Decode(valueHolder).Interface().([]CandidateLesson)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class MemoryCandidates", key))

		}
	}

}

func (c MemoryCandidates) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["exemplars"] = c.Exemplars

	fields["cautionaries"] = c.Cautionaries

	fields["lessons"] = c.Lessons

	return baml.EncodeClass("MemoryCandidates", fields, nil)
}

func (c MemoryCandidates) BamlTypeName() string {
	return "MemoryCandidates"
}

type MemoryContext struct {
	Exemplar_doctrines  []PastDoctrineExample `json:"exemplar_doctrines"`
	Cautionary_patterns []CautionaryPattern   `json:"cautionary_patterns"`
	Lessons             []MemoryLesson        `json:"lessons"`
}

func (c *MemoryContext) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "MemoryContext" {
		panic(fmt.Sprintf("expected MemoryContext, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "exemplar_doctrines":
			c.Exemplar_doctrines = baml.Decode(valueHolder).Interface().([]PastDoctrineExample)

		case "cautionary_patterns":
			c.Cautionary_patterns = baml.Decode(valueHolder).Interface().([]CautionaryPattern)

		case "lessons":
			c.Lessons = baml.Decode(valueHolder).Interface().([]MemoryLesson)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class MemoryContext", key))

		}
	}

}

func (c MemoryContext) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["exemplar_doctrines"] = c.Exemplar_doctrines

	fields["cautionary_patterns"] = c.Cautionary_patterns

	fields["lessons"] = c.Lessons

	return baml.EncodeClass("MemoryContext", fields, nil)
}

func (c MemoryContext) BamlTypeName() string {
	return "MemoryContext"
}

type MemoryLesson struct {
	Trigger  string `json:"trigger"`
	Guidance string `json:"guidance"`
}

func (c *MemoryLesson) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "MemoryLesson" {
		panic(fmt.Sprintf("expected MemoryLesson, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "trigger":
			c.Trigger = baml.Decode(valueHolder).Interface().(string)

		case "guidance":
			c.Guidance = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class MemoryLesson", key))

		}
	}

}

func (c MemoryLesson) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["trigger"] = c.Trigger

	fields["guidance"] = c.Guidance

	return baml.EncodeClass("MemoryLesson", fields, nil)
}

func (c MemoryLesson) BamlTypeName() string {
	return "MemoryLesson"
}

type PastDoctrineExample struct {
	Context          string `json:"context"`
	Rationale        string `json:"rationale"`
	Doctrine_summary string `json:"doctrine_summary"`
}

func (c *PastDoctrineExample) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "PastDoctrineExample" {
		panic(fmt.Sprintf("expected PastDoctrineExample, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "context":
			c.Context = baml.Decode(valueHolder).Interface().(string)

		case "rationale":
			c.Rationale = baml.Decode(valueHolder).Interface().(string)

		case "doctrine_summary":
			c.Doctrine_summary = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class PastDoctrineExample", key))

		}
	}

}

func (c PastDoctrineExample) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["context"] = c.Context

	fields["rationale"] = c.Rationale

	fields["doctrine_summary"] = c.Doctrine_summary

	return baml.EncodeClass("PastDoctrineExample", fields, nil)
}

func (c PastDoctrineExample) BamlTypeName() string {
	return "PastDoctrineExample"
}

type PowerStatus struct {
	Drained  int64  `json:"drained"`
	Provided int64  `json:"provided"`
	State    string `json:"state"`
}

func (c *PowerStatus) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "PowerStatus" {
		panic(fmt.Sprintf("expected PowerStatus, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "drained":
			c.Drained = baml.Decode(valueHolder).Int()

		case "provided":
			c.Provided = baml.Decode(valueHolder).Int()

		case "state":
			c.State = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class PowerStatus", key))

		}
	}

}

func (c PowerStatus) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["drained"] = c.Drained

	fields["provided"] = c.Provided

	fields["state"] = c.State

	return baml.EncodeClass("PowerStatus", fields, nil)
}

func (c PowerStatus) BamlTypeName() string {
	return "PowerStatus"
}

type RecentDoctrine struct {
	Tick  int64  `json:"tick"`
	Name  string `json:"name"`
	Shape string `json:"shape"`
}

func (c *RecentDoctrine) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "RecentDoctrine" {
		panic(fmt.Sprintf("expected RecentDoctrine, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "tick":
			c.Tick = baml.Decode(valueHolder).Int()

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(string)

		case "shape":
			c.Shape = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class RecentDoctrine", key))

		}
	}

}

func (c RecentDoctrine) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["tick"] = c.Tick

	fields["name"] = c.Name

	fields["shape"] = c.Shape

	return baml.EncodeClass("RecentDoctrine", fields, nil)
}

func (c RecentDoctrine) BamlTypeName() string {
	return "RecentDoctrine"
}

type RelevantMemory struct {
	Alignment_note string               `json:"alignment_note"`
	Exemplars      []SelectedExemplar   `json:"exemplars"`
	Cautionaries   []SelectedCautionary `json:"cautionaries"`
	Lesson_ids     []int64              `json:"lesson_ids"`
}

func (c *RelevantMemory) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "RelevantMemory" {
		panic(fmt.Sprintf("expected RelevantMemory, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "alignment_note":
			c.Alignment_note = baml.Decode(valueHolder).Interface().(string)

		case "exemplars":
			c.Exemplars = baml.Decode(valueHolder).Interface().([]SelectedExemplar)

		case "cautionaries":
			c.Cautionaries = baml.Decode(valueHolder).Interface().([]SelectedCautionary)

		case "lesson_ids":
			c.Lesson_ids = baml.Decode(valueHolder).Interface().([]int64)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class RelevantMemory", key))

		}
	}

}

func (c RelevantMemory) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["alignment_note"] = c.Alignment_note

	fields["exemplars"] = c.Exemplars

	fields["cautionaries"] = c.Cautionaries

	fields["lesson_ids"] = c.Lesson_ids

	return baml.EncodeClass("RelevantMemory", fields, nil)
}

func (c RelevantMemory) BamlTypeName() string {
	return "RelevantMemory"
}

type RetroLesson struct {
	Trigger_text  string  `json:"trigger_text"`
	Guidance_text string  `json:"guidance_text"`
	Confidence    float64 `json:"confidence"`
}

func (c *RetroLesson) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "RetroLesson" {
		panic(fmt.Sprintf("expected RetroLesson, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "trigger_text":
			c.Trigger_text = baml.Decode(valueHolder).Interface().(string)

		case "guidance_text":
			c.Guidance_text = baml.Decode(valueHolder).Interface().(string)

		case "confidence":
			c.Confidence = baml.Decode(valueHolder).Float()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class RetroLesson", key))

		}
	}

}

func (c RetroLesson) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["trigger_text"] = c.Trigger_text

	fields["guidance_text"] = c.Guidance_text

	fields["confidence"] = c.Confidence

	return baml.EncodeClass("RetroLesson", fields, nil)
}

func (c RetroLesson) BamlTypeName() string {
	return "RetroLesson"
}

type SelectedCautionary struct {
	Id            int64  `json:"id"`
	Why_relevant  string `json:"why_relevant"`
	What_to_avoid string `json:"what_to_avoid"`
}

func (c *SelectedCautionary) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "SelectedCautionary" {
		panic(fmt.Sprintf("expected SelectedCautionary, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "id":
			c.Id = baml.Decode(valueHolder).Int()

		case "why_relevant":
			c.Why_relevant = baml.Decode(valueHolder).Interface().(string)

		case "what_to_avoid":
			c.What_to_avoid = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class SelectedCautionary", key))

		}
	}

}

func (c SelectedCautionary) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["id"] = c.Id

	fields["why_relevant"] = c.Why_relevant

	fields["what_to_avoid"] = c.What_to_avoid

	return baml.EncodeClass("SelectedCautionary", fields, nil)
}

func (c SelectedCautionary) BamlTypeName() string {
	return "SelectedCautionary"
}

type SelectedExemplar struct {
	Id              int64  `json:"id"`
	Why_relevant    string `json:"why_relevant"`
	What_to_emulate string `json:"what_to_emulate"`
}

func (c *SelectedExemplar) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "SelectedExemplar" {
		panic(fmt.Sprintf("expected SelectedExemplar, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "id":
			c.Id = baml.Decode(valueHolder).Int()

		case "why_relevant":
			c.Why_relevant = baml.Decode(valueHolder).Interface().(string)

		case "what_to_emulate":
			c.What_to_emulate = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class SelectedExemplar", key))

		}
	}

}

func (c SelectedExemplar) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["id"] = c.Id

	fields["why_relevant"] = c.Why_relevant

	fields["what_to_emulate"] = c.What_to_emulate

	return baml.EncodeClass("SelectedExemplar", fields, nil)
}

func (c SelectedExemplar) BamlTypeName() string {
	return "SelectedExemplar"
}

type SquadInfo struct {
	Name       string `json:"name"`
	Role       string `json:"role"`
	Unit_count int64  `json:"unit_count"`
}

func (c *SquadInfo) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "SquadInfo" {
		panic(fmt.Sprintf("expected SquadInfo, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(string)

		case "role":
			c.Role = baml.Decode(valueHolder).Interface().(string)

		case "unit_count":
			c.Unit_count = baml.Decode(valueHolder).Int()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class SquadInfo", key))

		}
	}

}

func (c SquadInfo) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["role"] = c.Role

	fields["unit_count"] = c.Unit_count

	return baml.EncodeClass("SquadInfo", fields, nil)
}

func (c SquadInfo) BamlTypeName() string {
	return "SquadInfo"
}

type SuperweaponFire struct {
	Key          string `json:"key"`
	Total_fires  int64  `json:"total_fires"`
	Recent_fires int64  `json:"recent_fires"`
}

func (c *SuperweaponFire) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "SuperweaponFire" {
		panic(fmt.Sprintf("expected SuperweaponFire, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "key":
			c.Key = baml.Decode(valueHolder).Interface().(string)

		case "total_fires":
			c.Total_fires = baml.Decode(valueHolder).Int()

		case "recent_fires":
			c.Recent_fires = baml.Decode(valueHolder).Int()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class SuperweaponFire", key))

		}
	}

}

func (c SuperweaponFire) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["key"] = c.Key

	fields["total_fires"] = c.Total_fires

	fields["recent_fires"] = c.Recent_fires

	return baml.EncodeClass("SuperweaponFire", fields, nil)
}

func (c SuperweaponFire) BamlTypeName() string {
	return "SuperweaponFire"
}

type SupportPowerStatus struct {
	Key    string `json:"key"`
	Status string `json:"status"`
}

func (c *SupportPowerStatus) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "SupportPowerStatus" {
		panic(fmt.Sprintf("expected SupportPowerStatus, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "key":
			c.Key = baml.Decode(valueHolder).Interface().(string)

		case "status":
			c.Status = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class SupportPowerStatus", key))

		}
	}

}

func (c SupportPowerStatus) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["key"] = c.Key

	fields["status"] = c.Status

	return baml.EncodeClass("SupportPowerStatus", fields, nil)
}

func (c SupportPowerStatus) BamlTypeName() string {
	return "SupportPowerStatus"
}

type TurningPoint struct {
	Tick                      int64  `json:"tick"`
	What_happened             string `json:"what_happened"`
	What_should_have_happened string `json:"what_should_have_happened"`
}

func (c *TurningPoint) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "TurningPoint" {
		panic(fmt.Sprintf("expected TurningPoint, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "tick":
			c.Tick = baml.Decode(valueHolder).Int()

		case "what_happened":
			c.What_happened = baml.Decode(valueHolder).Interface().(string)

		case "what_should_have_happened":
			c.What_should_have_happened = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class TurningPoint", key))

		}
	}

}

func (c TurningPoint) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["tick"] = c.Tick

	fields["what_happened"] = c.What_happened

	fields["what_should_have_happened"] = c.What_should_have_happened

	return baml.EncodeClass("TurningPoint", fields, nil)
}

func (c TurningPoint) BamlTypeName() string {
	return "TurningPoint"
}

type TypeCount struct {
	Type  string `json:"type"`
	Count int64  `json:"count"`
}

func (c *TypeCount) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "TypeCount" {
		panic(fmt.Sprintf("expected TypeCount, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "type":
			c.Type = baml.Decode(valueHolder).Interface().(string)

		case "count":
			c.Count = baml.Decode(valueHolder).Int()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class TypeCount", key))

		}
	}

}

func (c TypeCount) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["type"] = c.Type

	fields["count"] = c.Count

	return baml.EncodeClass("TypeCount", fields, nil)
}

func (c TypeCount) BamlTypeName() string {
	return "TypeCount"
}
