// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type ActiveProductionClassView struct {
	inner baml.ClassBuilder
}

func (t *ActiveProductionClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ActiveProductionClassView) PropertyQueue() (ClassPropertyView, error) {
	return t.inner.Property("queue")
}

func (t *ActiveProductionClassView) PropertyItem() (ClassPropertyView, error) {
	return t.inner.Property("item")
}

func (t *ActiveProductionClassView) PropertyProgress() (ClassPropertyView, error) {
	return t.inner.Property("progress")
}

func (t *TypeBuilder) ActiveProduction() (*ActiveProductionClassView, error) {
	bld, err := t.inner.Class("ActiveProduction")
	if err != nil {
		return nil, err
	}
	return &ActiveProductionClassView{inner: bld}, nil
}

func (t *ActiveProductionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CandidateCautionaryClassView struct {
	inner baml.ClassBuilder
}

func (t *CandidateCautionaryClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CandidateCautionaryClassView) PropertyId() (ClassPropertyView, error) {
	return t.inner.Property("id")
}

func (t *CandidateCautionaryClassView) PropertyContext() (ClassPropertyView, error) {
	return t.inner.Property("context")
}

func (t *CandidateCautionaryClassView) PropertyFailed_pattern() (ClassPropertyView, error) {
	return t.inner.Property("failed_pattern")
}

func (t *CandidateCautionaryClassView) PropertyFailure_reason() (ClassPropertyView, error) {
	return t.inner.Property("failure_reason")
}

func (t *TypeBuilder) CandidateCautionary() (*CandidateCautionaryClassView, error) {
	bld, err := t.inner.Class("CandidateCautionary")
	if err != nil {
		return nil, err
	}
	return &CandidateCautionaryClassView{inner: bld}, nil
}

func (t *CandidateCautionaryClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CandidateExemplarClassView struct {
	inner baml.ClassBuilder
}

func (t *CandidateExemplarClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CandidateExemplarClassView) PropertyId() (ClassPropertyView, error) {
	return t.inner.Property("id")
}

func (t *CandidateExemplarClassView) PropertyContext() (ClassPropertyView, error) {
	return t.inner.Property("context")
}

func (t *CandidateExemplarClassView) PropertyRationale() (ClassPropertyView, error) {
	return t.inner.Property("rationale")
}

func (t *CandidateExemplarClassView) PropertyDoctrine_summary() (ClassPropertyView, error) {
	return t.inner.Property("doctrine_summary")
}

func (t *TypeBuilder) CandidateExemplar() (*CandidateExemplarClassView, error) {
	bld, err := t.inner.Class("CandidateExemplar")
	if err != nil {
		return nil, err
	}
	return &CandidateExemplarClassView{inner: bld}, nil
}

func (t *CandidateExemplarClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CandidateLessonClassView struct {
	inner baml.ClassBuilder
}

func (t *CandidateLessonClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CandidateLessonClassView) PropertyId() (ClassPropertyView, error) {
	return t.inner.Property("id")
}

func (t *CandidateLessonClassView) PropertyTrigger() (ClassPropertyView, error) {
	return t.inner.Property("trigger")
}

func (t *CandidateLessonClassView) PropertyGuidance() (ClassPropertyView, error) {
	return t.inner.Property("guidance")
}

func (t *CandidateLessonClassView) PropertyConfidence() (ClassPropertyView, error) {
	return t.inner.Property("confidence")
}

func (t *TypeBuilder) CandidateLesson() (*CandidateLessonClassView, error) {
	bld, err := t.inner.Class("CandidateLesson")
	if err != nil {
		return nil, err
	}
	return &CandidateLessonClassView{inner: bld}, nil
}

func (t *CandidateLessonClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CautionaryPatternClassView struct {
	inner baml.ClassBuilder
}

func (t *CautionaryPatternClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CautionaryPatternClassView) PropertyContext() (ClassPropertyView, error) {
	return t.inner.Property("context")
}

func (t *CautionaryPatternClassView) PropertyFailed_pattern() (ClassPropertyView, error) {
	return t.inner.Property("failed_pattern")
}

func (t *CautionaryPatternClassView) PropertyFailure_reason() (ClassPropertyView, error) {
	return t.inner.Property("failure_reason")
}

func (t *TypeBuilder) CautionaryPattern() (*CautionaryPatternClassView, error) {
	bld, err := t.inner.Class("CautionaryPattern")
	if err != nil {
		return nil, err
	}
	return &CautionaryPatternClassView{inner: bld}, nil
}

func (t *CautionaryPatternClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CombatStatsClassView struct {
	inner baml.ClassBuilder
}

func (t *CombatStatsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CombatStatsClassView) PropertyInfantry_lost() (ClassPropertyView, error) {
	return t.inner.Property("infantry_lost")
}

func (t *CombatStatsClassView) PropertyVehicles_lost() (ClassPropertyView, error) {
	return t.inner.Property("vehicles_lost")
}

func (t *CombatStatsClassView) PropertyAircraft_lost() (ClassPropertyView, error) {
	return t.inner.Property("aircraft_lost")
}

func (t *CombatStatsClassView) PropertyNaval_lost() (ClassPropertyView, error) {
	return t.inner.Property("naval_lost")
}

func (t *TypeBuilder) CombatStats() (*CombatStatsClassView, error) {
	bld, err := t.inner.Class("CombatStats")
	if err != nil {
		return nil, err
	}
	return &CombatStatsClassView{inner: bld}, nil
}

func (t *CombatStatsClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DoctrineClassView struct {
	inner baml.ClassBuilder
}

func (t *DoctrineClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DoctrineClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *DoctrineClassView) PropertyRationale() (ClassPropertyView, error) {
	return t.inner.Property("rationale")
}

func (t *DoctrineClassView) PropertyEconomy_priority() (ClassPropertyView, error) {
	return t.inner.Property("economy_priority")
}

func (t *DoctrineClassView) PropertyAggression() (ClassPropertyView, error) {
	return t.inner.Property("aggression")
}

func (t *DoctrineClassView) PropertyGround_defense_priority() (ClassPropertyView, error) {
	return t.inner.Property("ground_defense_priority")
}

func (t *DoctrineClassView) PropertyAir_defense_priority() (ClassPropertyView, error) {
	return t.inner.Property("air_defense_priority")
}

func (t *DoctrineClassView) PropertyTech_priority() (ClassPropertyView, error) {
	return t.inner.Property("tech_priority")
}

func (t *DoctrineClassView) PropertyInfantry_weight() (ClassPropertyView, error) {
	return t.inner.Property("infantry_weight")
}

func (t *DoctrineClassView) PropertyVehicle_weight() (ClassPropertyView, error) {
	return t.inner.Property("vehicle_weight")
}

func (t *DoctrineClassView) PropertyAir_weight() (ClassPropertyView, error) {
	return t.inner.Property("air_weight")
}

func (t *DoctrineClassView) PropertyNaval_weight() (ClassPropertyView, error) {
	return t.inner.Property("naval_weight")
}

func (t *DoctrineClassView) PropertyGround_attack_group_size() (ClassPropertyView, error) {
	return t.inner.Property("ground_attack_group_size")
}

func (t *DoctrineClassView) PropertyAir_attack_group_size() (ClassPropertyView, error) {
	return t.inner.Property("air_attack_group_size")
}

func (t *DoctrineClassView) PropertyNaval_attack_group_size() (ClassPropertyView, error) {
	return t.inner.Property("naval_attack_group_size")
}

func (t *DoctrineClassView) PropertyScout_priority() (ClassPropertyView, error) {
	return t.inner.Property("scout_priority")
}

func (t *DoctrineClassView) PropertySpecialized_infantry_weight() (ClassPropertyView, error) {
	return t.inner.Property("specialized_infantry_weight")
}

func (t *DoctrineClassView) PropertySuperweapon_priority() (ClassPropertyView, error) {
	return t.inner.Property("superweapon_priority")
}

func (t *DoctrineClassView) PropertyCapture_priority() (ClassPropertyView, error) {
	return t.inner.Property("capture_priority")
}

func (t *DoctrineClassView) PropertyTransport_assault() (ClassPropertyView, error) {
	return t.inner.Property("transport_assault")
}

func (t *DoctrineClassView) PropertyPreferred_infantry() (ClassPropertyView, error) {
	return t.inner.Property("preferred_infantry")
}

func (t *DoctrineClassView) PropertyPreferred_vehicle() (ClassPropertyView, error) {
	return t.inner.Property("preferred_vehicle")
}

func (t *DoctrineClassView) PropertyPreferred_aircraft() (ClassPropertyView, error) {
	return t.inner.Property("preferred_aircraft")
}

func (t *DoctrineClassView) PropertyPreferred_naval() (ClassPropertyView, error) {
	return t.inner.Property("preferred_naval")
}

func (t *DoctrineClassView) PropertyGround_target_aa_priority() (ClassPropertyView, error) {
	return t.inner.Property("ground_target_aa_priority")
}

func (t *DoctrineClassView) PropertyAir_target_ground_def_priority() (ClassPropertyView, error) {
	return t.inner.Property("air_target_ground_def_priority")
}

func (t *DoctrineClassView) PropertyCommit_ratio() (ClassPropertyView, error) {
	return t.inner.Property("commit_ratio")
}

func (t *DoctrineClassView) PropertyBase_defense_floor() (ClassPropertyView, error) {
	return t.inner.Property("base_defense_floor")
}

func (t *DoctrineClassView) PropertyRepair_budget_ratio() (ClassPropertyView, error) {
	return t.inner.Property("repair_budget_ratio")
}

func (t *DoctrineClassView) PropertyScout_reach_priority() (ClassPropertyView, error) {
	return t.inner.Property("scout_reach_priority")
}

func (t *TypeBuilder) Doctrine() (*DoctrineClassView, error) {
	bld, err := t.inner.Class("Doctrine")
	if err != nil {
		return nil, err
	}
	return &DoctrineClassView{inner: bld}, nil
}

func (t *DoctrineClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DoctrineHistoryEntryClassView struct {
	inner baml.ClassBuilder
}

func (t *DoctrineHistoryEntryClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DoctrineHistoryEntryClassView) PropertyTick() (ClassPropertyView, error) {
	return t.inner.Property("tick")
}

func (t *DoctrineHistoryEntryClassView) PropertyDoctrine() (ClassPropertyView, error) {
	return t.inner.Property("doctrine")
}

func (t *TypeBuilder) DoctrineHistoryEntry() (*DoctrineHistoryEntryClassView, error) {
	bld, err := t.inner.Class("DoctrineHistoryEntry")
	if err != nil {
		return nil, err
	}
	return &DoctrineHistoryEntryClassView{inner: bld}, nil
}

func (t *DoctrineHistoryEntryClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DoctrineRatingClassView struct {
	inner baml.ClassBuilder
}

func (t *DoctrineRatingClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DoctrineRatingClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *DoctrineRatingClassView) PropertyRating() (ClassPropertyView, error) {
	return t.inner.Property("rating")
}

func (t *DoctrineRatingClassView) PropertyReasoning() (ClassPropertyView, error) {
	return t.inner.Property("reasoning")
}

func (t *TypeBuilder) DoctrineRating() (*DoctrineRatingClassView, error) {
	bld, err := t.inner.Class("DoctrineRating")
	if err != nil {
		return nil, err
	}
	return &DoctrineRatingClassView{inner: bld}, nil
}

func (t *DoctrineRatingClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type EnemyBaseClassView struct {
	inner baml.ClassBuilder
}

func (t *EnemyBaseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *EnemyBaseClassView) PropertyOwner() (ClassPropertyView, error) {
	return t.inner.Property("owner")
}

func (t *EnemyBaseClassView) PropertyX() (ClassPropertyView, error) {
	return t.inner.Property("x")
}

func (t *EnemyBaseClassView) PropertyY() (ClassPropertyView, error) {
	return t.inner.Property("y")
}

func (t *EnemyBaseClassView) PropertyLast_seen_tick() (ClassPropertyView, error) {
	return t.inner.Property("last_seen_tick")
}

func (t *TypeBuilder) EnemyBase() (*EnemyBaseClassView, error) {
	bld, err := t.inner.Class("EnemyBase")
	if err != nil {
		return nil, err
	}
	return &EnemyBaseClassView{inner: bld}, nil
}

func (t *EnemyBaseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GameEventClassView struct {
	inner baml.ClassBuilder
}

func (t *GameEventClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GameEventClassView) PropertyKind() (ClassPropertyView, error) {
	return t.inner.Property("kind")
}

func (t *GameEventClassView) PropertyTick() (ClassPropertyView, error) {
	return t.inner.Property("tick")
}

func (t *GameEventClassView) PropertyDetail() (ClassPropertyView, error) {
	return t.inner.Property("detail")
}

func (t *TypeBuilder) GameEvent() (*GameEventClassView, error) {
	bld, err := t.inner.Class("GameEvent")
	if err != nil {
		return nil, err
	}
	return &GameEventClassView{inner: bld}, nil
}

func (t *GameEventClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GameReviewClassView struct {
	inner baml.ClassBuilder
}

func (t *GameReviewClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GameReviewClassView) PropertySummary() (ClassPropertyView, error) {
	return t.inner.Property("summary")
}

func (t *GameReviewClassView) PropertyQuality_tag() (ClassPropertyView, error) {
	return t.inner.Property("quality_tag")
}

func (t *GameReviewClassView) PropertyTurning_points() (ClassPropertyView, error) {
	return t.inner.Property("turning_points")
}

func (t *GameReviewClassView) PropertyDoctrine_ratings() (ClassPropertyView, error) {
	return t.inner.Property("doctrine_ratings")
}

func (t *GameReviewClassView) PropertyLessons() (ClassPropertyView, error) {
	return t.inner.Property("lessons")
}

func (t *TypeBuilder) GameReview() (*GameReviewClassView, error) {
	bld, err := t.inner.Class("GameReview")
	if err != nil {
		return nil, err
	}
	return &GameReviewClassView{inner: bld}, nil
}

func (t *GameReviewClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GameSituationClassView struct {
	inner baml.ClassBuilder
}

func (t *GameSituationClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GameSituationClassView) PropertyTick() (ClassPropertyView, error) {
	return t.inner.Property("tick")
}

func (t *GameSituationClassView) PropertyPhase() (ClassPropertyView, error) {
	return t.inner.Property("phase")
}

func (t *GameSituationClassView) PropertyCash() (ClassPropertyView, error) {
	return t.inner.Property("cash")
}

func (t *GameSituationClassView) PropertyResources() (ClassPropertyView, error) {
	return t.inner.Property("resources")
}

func (t *GameSituationClassView) PropertyResource_capacity() (ClassPropertyView, error) {
	return t.inner.Property("resource_capacity")
}

func (t *GameSituationClassView) PropertyPower() (ClassPropertyView, error) {
	return t.inner.Property("power")
}

func (t *GameSituationClassView) PropertyBuildings() (ClassPropertyView, error) {
	return t.inner.Property("buildings")
}

func (t *GameSituationClassView) PropertyUnits() (ClassPropertyView, error) {
	return t.inner.Property("units")
}

func (t *GameSituationClassView) PropertyIdle_unit_count() (ClassPropertyView, error) {
	return t.inner.Property("idle_unit_count")
}

func (t *GameSituationClassView) PropertyActive_production() (ClassPropertyView, error) {
	return t.inner.Property("active_production")
}

func (t *GameSituationClassView) PropertySupport_powers() (ClassPropertyView, error) {
	return t.inner.Property("support_powers")
}

func (t *GameSituationClassView) PropertySuperweapon_fires() (ClassPropertyView, error) {
	return t.inner.Property("superweapon_fires")
}

func (t *GameSituationClassView) PropertySquads() (ClassPropertyView, error) {
	return t.inner.Property("squads")
}

func (t *GameSituationClassView) PropertyEnemies_visible() (ClassPropertyView, error) {
	return t.inner.Property("enemies_visible")
}

func (t *GameSituationClassView) PropertyEnemy_units() (ClassPropertyView, error) {
	return t.inner.Property("enemy_units")
}

func (t *GameSituationClassView) PropertyEnemy_units_seen() (ClassPropertyView, error) {
	return t.inner.Property("enemy_units_seen")
}

func (t *GameSituationClassView) PropertyEnemy_buildings() (ClassPropertyView, error) {
	return t.inner.Property("enemy_buildings")
}

func (t *GameSituationClassView) PropertyEnemy_buildings_seen() (ClassPropertyView, error) {
	return t.inner.Property("enemy_buildings_seen")
}

func (t *GameSituationClassView) PropertyKnown_enemy_bases() (ClassPropertyView, error) {
	return t.inner.Property("known_enemy_bases")
}

func (t *GameSituationClassView) PropertyMap_width() (ClassPropertyView, error) {
	return t.inner.Property("map_width")
}

func (t *GameSituationClassView) PropertyMap_height() (ClassPropertyView, error) {
	return t.inner.Property("map_height")
}

func (t *GameSituationClassView) PropertyRecent_events() (ClassPropertyView, error) {
	return t.inner.Property("recent_events")
}

func (t *GameSituationClassView) PropertyCombat_stats() (ClassPropertyView, error) {
	return t.inner.Property("combat_stats")
}

func (t *GameSituationClassView) PropertyRecent_doctrines() (ClassPropertyView, error) {
	return t.inner.Property("recent_doctrines")
}

func (t *GameSituationClassView) PropertyBurned_axes() (ClassPropertyView, error) {
	return t.inner.Property("burned_axes")
}

func (t *GameSituationClassView) PropertyCapturables_visible() (ClassPropertyView, error) {
	return t.inner.Property("capturables_visible")
}

func (t *GameSituationClassView) PropertyBeing_rushed() (ClassPropertyView, error) {
	return t.inner.Property("being_rushed")
}

func (t *GameSituationClassView) PropertyHarvester_harassed() (ClassPropertyView, error) {
	return t.inner.Property("harvester_harassed")
}

func (t *GameSituationClassView) PropertyGround_squad_ready_ratio() (ClassPropertyView, error) {
	return t.inner.Property("ground_squad_ready_ratio")
}

func (t *GameSituationClassView) PropertyCash_burn_rate() (ClassPropertyView, error) {
	return t.inner.Property("cash_burn_rate")
}

func (t *GameSituationClassView) PropertyFaction_side() (ClassPropertyView, error) {
	return t.inner.Property("faction_side")
}

func (t *GameSituationClassView) PropertyUnbuildable_roles() (ClassPropertyView, error) {
	return t.inner.Property("unbuildable_roles")
}

func (t *GameSituationClassView) PropertyHarvester_share() (ClassPropertyView, error) {
	return t.inner.Property("harvester_share")
}

func (t *GameSituationClassView) PropertyOur_combat_units() (ClassPropertyView, error) {
	return t.inner.Property("our_combat_units")
}

func (t *GameSituationClassView) PropertyEnemy_combat_units_seen() (ClassPropertyView, error) {
	return t.inner.Property("enemy_combat_units_seen")
}

func (t *GameSituationClassView) PropertyTime_to_reach_enemy_estimate() (ClassPropertyView, error) {
	return t.inner.Property("time_to_reach_enemy_estimate")
}

func (t *TypeBuilder) GameSituation() (*GameSituationClassView, error) {
	bld, err := t.inner.Class("GameSituation")
	if err != nil {
		return nil, err
	}
	return &GameSituationClassView{inner: bld}, nil
}

func (t *GameSituationClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MemoryCandidatesClassView struct {
	inner baml.ClassBuilder
}

func (t *MemoryCandidatesClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MemoryCandidatesClassView) PropertyExemplars() (ClassPropertyView, error) {
	return t.inner.Property("exemplars")
}

func (t *MemoryCandidatesClassView) PropertyCautionaries() (ClassPropertyView, error) {
	return t.inner.Property("cautionaries")
}

func (t *MemoryCandidatesClassView) PropertyLessons() (ClassPropertyView, error) {
	return t.inner.Property("lessons")
}

func (t *TypeBuilder) MemoryCandidates() (*MemoryCandidatesClassView, error) {
	bld, err := t.inner.Class("MemoryCandidates")
	if err != nil {
		return nil, err
	}
	return &MemoryCandidatesClassView{inner: bld}, nil
}

func (t *MemoryCandidatesClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MemoryContextClassView struct {
	inner baml.ClassBuilder
}

func (t *MemoryContextClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MemoryContextClassView) PropertyExemplar_doctrines() (ClassPropertyView, error) {
	return t.inner.Property("exemplar_doctrines")
}

func (t *MemoryContextClassView) PropertyCautionary_patterns() (ClassPropertyView, error) {
	return t.inner.Property("cautionary_patterns")
}

func (t *MemoryContextClassView) PropertyLessons() (ClassPropertyView, error) {
	return t.inner.Property("lessons")
}

func (t *TypeBuilder) MemoryContext() (*MemoryContextClassView, error) {
	bld, err := t.inner.Class("MemoryContext")
	if err != nil {
		return nil, err
	}
	return &MemoryContextClassView{inner: bld}, nil
}

func (t *MemoryContextClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MemoryLessonClassView struct {
	inner baml.ClassBuilder
}

func (t *MemoryLessonClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MemoryLessonClassView) PropertyTrigger() (ClassPropertyView, error) {
	return t.inner.Property("trigger")
}

func (t *MemoryLessonClassView) PropertyGuidance() (ClassPropertyView, error) {
	return t.inner.Property("guidance")
}

func (t *TypeBuilder) MemoryLesson() (*MemoryLessonClassView, error) {
	bld, err := t.inner.Class("MemoryLesson")
	if err != nil {
		return nil, err
	}
	return &MemoryLessonClassView{inner: bld}, nil
}

func (t *MemoryLessonClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PastDoctrineExampleClassView struct {
	inner baml.ClassBuilder
}

func (t *PastDoctrineExampleClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *PastDoctrineExampleClassView) PropertyContext() (ClassPropertyView, error) {
	return t.inner.Property("context")
}

func (t *PastDoctrineExampleClassView) PropertyRationale() (ClassPropertyView, error) {
	return t.inner.Property("rationale")
}

func (t *PastDoctrineExampleClassView) PropertyDoctrine_summary() (ClassPropertyView, error) {
	return t.inner.Property("doctrine_summary")
}

func (t *TypeBuilder) PastDoctrineExample() (*PastDoctrineExampleClassView, error) {
	bld, err := t.inner.Class("PastDoctrineExample")
	if err != nil {
		return nil, err
	}
	return &PastDoctrineExampleClassView{inner: bld}, nil
}

func (t *PastDoctrineExampleClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PowerStatusClassView struct {
	inner baml.ClassBuilder
}

func (t *PowerStatusClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *PowerStatusClassView) PropertyDrained() (ClassPropertyView, error) {
	return t.inner.Property("drained")
}

func (t *PowerStatusClassView) PropertyProvided() (ClassPropertyView, error) {
	return t.inner.Property("provided")
}

func (t *PowerStatusClassView) PropertyState() (ClassPropertyView, error) {
	return t.inner.Property("state")
}

func (t *TypeBuilder) PowerStatus() (*PowerStatusClassView, error) {
	bld, err := t.inner.Class("PowerStatus")
	if err != nil {
		return nil, err
	}
	return &PowerStatusClassView{inner: bld}, nil
}

func (t *PowerStatusClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type RecentDoctrineClassView struct {
	inner baml.ClassBuilder
}

func (t *RecentDoctrineClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *RecentDoctrineClassView) PropertyTick() (ClassPropertyView, error) {
	return t.inner.Property("tick")
}

func (t *RecentDoctrineClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *RecentDoctrineClassView) PropertyShape() (ClassPropertyView, error) {
	return t.inner.Property("shape")
}

func (t *TypeBuilder) RecentDoctrine() (*RecentDoctrineClassView, error) {
	bld, err := t.inner.Class("RecentDoctrine")
	if err != nil {
		return nil, err
	}
	return &RecentDoctrineClassView{inner: bld}, nil
}

func (t *RecentDoctrineClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type RelevantMemoryClassView struct {
	inner baml.ClassBuilder
}

func (t *RelevantMemoryClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *RelevantMemoryClassView) PropertyAlignment_note() (ClassPropertyView, error) {
	return t.inner.Property("alignment_note")
}

func (t *RelevantMemoryClassView) PropertyExemplars() (ClassPropertyView, error) {
	return t.inner.Property("exemplars")
}

func (t *RelevantMemoryClassView) PropertyCautionaries() (ClassPropertyView, error) {
	return t.inner.Property("cautionaries")
}

func (t *RelevantMemoryClassView) PropertyLesson_ids() (ClassPropertyView, error) {
	return t.inner.Property("lesson_ids")
}

func (t *TypeBuilder) RelevantMemory() (*RelevantMemoryClassView, error) {
	bld, err := t.inner.Class("RelevantMemory")
	if err != nil {
		return nil, err
	}
	return &RelevantMemoryClassView{inner: bld}, nil
}

func (t *RelevantMemoryClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type RetroLessonClassView struct {
	inner baml.ClassBuilder
}

func (t *RetroLessonClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *RetroLessonClassView) PropertyTrigger_text() (ClassPropertyView, error) {
	return t.inner.Property("trigger_text")
}

func (t *RetroLessonClassView) PropertyGuidance_text() (ClassPropertyView, error) {
	return t.inner.Property("guidance_text")
}

func (t *RetroLessonClassView) PropertyConfidence() (ClassPropertyView, error) {
	return t.inner.Property("confidence")
}

func (t *TypeBuilder) RetroLesson() (*RetroLessonClassView, error) {
	bld, err := t.inner.Class("RetroLesson")
	if err != nil {
		return nil, err
	}
	return &RetroLessonClassView{inner: bld}, nil
}

func (t *RetroLessonClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SelectedCautionaryClassView struct {
	inner baml.ClassBuilder
}

func (t *SelectedCautionaryClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SelectedCautionaryClassView) PropertyId() (ClassPropertyView, error) {
	return t.inner.Property("id")
}

func (t *SelectedCautionaryClassView) PropertyWhy_relevant() (ClassPropertyView, error) {
	return t.inner.Property("why_relevant")
}

func (t *SelectedCautionaryClassView) PropertyWhat_to_avoid() (ClassPropertyView, error) {
	return t.inner.Property("what_to_avoid")
}

func (t *TypeBuilder) SelectedCautionary() (*SelectedCautionaryClassView, error) {
	bld, err := t.inner.Class("SelectedCautionary")
	if err != nil {
		return nil, err
	}
	return &SelectedCautionaryClassView{inner: bld}, nil
}

func (t *SelectedCautionaryClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SelectedExemplarClassView struct {
	inner baml.ClassBuilder
}

func (t *SelectedExemplarClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SelectedExemplarClassView) PropertyId() (ClassPropertyView, error) {
	return t.inner.Property("id")
}

func (t *SelectedExemplarClassView) PropertyWhy_relevant() (ClassPropertyView, error) {
	return t.inner.Property("why_relevant")
}

func (t *SelectedExemplarClassView) PropertyWhat_to_emulate() (ClassPropertyView, error) {
	return t.inner.Property("what_to_emulate")
}

func (t *TypeBuilder) SelectedExemplar() (*SelectedExemplarClassView, error) {
	bld, err := t.inner.Class("SelectedExemplar")
	if err != nil {
		return nil, err
	}
	return &SelectedExemplarClassView{inner: bld}, nil
}

func (t *SelectedExemplarClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SquadInfoClassView struct {
	inner baml.ClassBuilder
}

func (t *SquadInfoClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SquadInfoClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *SquadInfoClassView) PropertyRole() (ClassPropertyView, error) {
	return t.inner.Property("role")
}

func (t *SquadInfoClassView) PropertyUnit_count() (ClassPropertyView, error) {
	return t.inner.Property("unit_count")
}

func (t *TypeBuilder) SquadInfo() (*SquadInfoClassView, error) {
	bld, err := t.inner.Class("SquadInfo")
	if err != nil {
		return nil, err
	}
	return &SquadInfoClassView{inner: bld}, nil
}

func (t *SquadInfoClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SuperweaponFireClassView struct {
	inner baml.ClassBuilder
}

func (t *SuperweaponFireClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SuperweaponFireClassView) PropertyKey() (ClassPropertyView, error) {
	return t.inner.Property("key")
}

func (t *SuperweaponFireClassView) PropertyTotal_fires() (ClassPropertyView, error) {
	return t.inner.Property("total_fires")
}

func (t *SuperweaponFireClassView) PropertyRecent_fires() (ClassPropertyView, error) {
	return t.inner.Property("recent_fires")
}

func (t *TypeBuilder) SuperweaponFire() (*SuperweaponFireClassView, error) {
	bld, err := t.inner.Class("SuperweaponFire")
	if err != nil {
		return nil, err
	}
	return &SuperweaponFireClassView{inner: bld}, nil
}

func (t *SuperweaponFireClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SupportPowerStatusClassView struct {
	inner baml.ClassBuilder
}

func (t *SupportPowerStatusClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SupportPowerStatusClassView) PropertyKey() (ClassPropertyView, error) {
	return t.inner.Property("key")
}

func (t *SupportPowerStatusClassView) PropertyStatus() (ClassPropertyView, error) {
	return t.inner.Property("status")
}

func (t *TypeBuilder) SupportPowerStatus() (*SupportPowerStatusClassView, error) {
	bld, err := t.inner.Class("SupportPowerStatus")
	if err != nil {
		return nil, err
	}
	return &SupportPowerStatusClassView{inner: bld}, nil
}

func (t *SupportPowerStatusClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TurningPointClassView struct {
	inner baml.ClassBuilder
}

func (t *TurningPointClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TurningPointClassView) PropertyTick() (ClassPropertyView, error) {
	return t.inner.Property("tick")
}

func (t *TurningPointClassView) PropertyWhat_happened() (ClassPropertyView, error) {
	return t.inner.Property("what_happened")
}

func (t *TurningPointClassView) PropertyWhat_should_have_happened() (ClassPropertyView, error) {
	return t.inner.Property("what_should_have_happened")
}

func (t *TypeBuilder) TurningPoint() (*TurningPointClassView, error) {
	bld, err := t.inner.Class("TurningPoint")
	if err != nil {
		return nil, err
	}
	return &TurningPointClassView{inner: bld}, nil
}

func (t *TurningPointClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TypeCountClassView struct {
	inner baml.ClassBuilder
}

func (t *TypeCountClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TypeCountClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *TypeCountClassView) PropertyCount() (ClassPropertyView, error) {
	return t.inner.Property("count")
}

func (t *TypeBuilder) TypeCount() (*TypeCountClassView, error) {
	bld, err := t.inner.Class("TypeCount")
	if err != nil {
		return nil, err
	}
	return &TypeCountClassView{inner: bld}, nil
}

func (t *TypeCountClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
