// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/nstehr/vimy/currie/baml_client/stream_types"
	"github.com/nstehr/vimy/currie/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.BlockedClause":            reflect.TypeOf(types.BlockedClause{}),
	"STREAM_TYPES.BlockedClause":     reflect.TypeOf(stream_types.BlockedClause{}),
	"TYPES.ClauseSensitivity":        reflect.TypeOf(types.ClauseSensitivity{}),
	"STREAM_TYPES.ClauseSensitivity": reflect.TypeOf(stream_types.ClauseSensitivity{}),
	"TYPES.DeadRule":                 reflect.TypeOf(types.DeadRule{}),
	"STREAM_TYPES.DeadRule":          reflect.TypeOf(stream_types.DeadRule{}),
	"TYPES.DirectiveAdvice":          reflect.TypeOf(types.DirectiveAdvice{}),
	"STREAM_TYPES.DirectiveAdvice":   reflect.TypeOf(stream_types.DirectiveAdvice{}),
	"TYPES.DoctrineChoice":           reflect.TypeOf(types.DoctrineChoice{}),
	"STREAM_TYPES.DoctrineChoice":    reflect.TypeOf(stream_types.DoctrineChoice{}),
	"TYPES.Finding":                  reflect.TypeOf(types.Finding{}),
	"STREAM_TYPES.Finding":           reflect.TypeOf(stream_types.Finding{}),
	"TYPES.GameFacts":                reflect.TypeOf(types.GameFacts{}),
	"STREAM_TYPES.GameFacts":         reflect.TypeOf(stream_types.GameFacts{}),
	"TYPES.Insight":                  reflect.TypeOf(types.Insight{}),
	"STREAM_TYPES.Insight":           reflect.TypeOf(stream_types.Insight{}),
	"TYPES.MissingThing":             reflect.TypeOf(types.MissingThing{}),
	"STREAM_TYPES.MissingThing":      reflect.TypeOf(stream_types.MissingThing{}),
	"TYPES.TunableGate":              reflect.TypeOf(types.TunableGate{}),
	"STREAM_TYPES.TunableGate":       reflect.TypeOf(stream_types.TunableGate{}),
}
