package rules

// ActionRegistry maps action ids to their functions, for the rule-set authoring
// path where a `do` field names an action by id rather than Go symbol. Keys are
// kebab to match that language. Nothing reads it yet — the compiler references
// the functions directly.
var ActionRegistry = map[string]ActionFunc{
	"produce-mcv":                 ActionProduceMCV,
	"deploy-mcv":                  ActionDeployMCV,
	"produce-power-plant":         ActionProducePowerPlant,
	"produce-refinery":            ActionProduceRefinery,
	"produce-barracks":            ActionProduceBarracks,
	"produce-war-factory":         ActionProduceWarFactory,
	"produce-radar":               ActionProduceRadar,
	"produce-airfield":            ActionProduceAirfield,
	"produce-naval-yard":          ActionProduceNavalYard,
	"produce-service-depot":       ActionProduceServiceDepot,
	"place-building":              ActionPlaceBuilding,
	"produce-infantry":            ActionProduceInfantry,
	"produce-vehicle":             ActionProduceVehicle,
	"produce-aircraft":            ActionProduceAircraft,
	"produce-ship":                ActionProduceShip,
	"place-defense":               ActionPlaceDefense,
	"produce-defense":             ActionProduceDefense,
	"produce-aa-defense":          ActionProduceAADefense,
	"produce-tech-center":         ActionProduceTechCenter,
	"produce-heavy-vehicle":       ActionProduceHeavyVehicle,
	"produce-rocket-soldier":      ActionProduceRocketSoldier,
	"produce-specialist-infantry": ActionProduceSpecialistInfantry,
	"produce-advanced-aircraft":   ActionProduceAdvancedAircraft,
	"produce-advanced-power":      ActionProduceAdvancedPower,
	"produce-ore-silo":            ActionProduceOreSilo,
	"produce-advanced-ship":       ActionProduceAdvancedShip,
	"defend-base":                 ActionDefendBase,
	"emergency-defend-base":       ActionEmergencyDefendBase,
	"air-defend-base":             ActionAirDefendBase,
	"repair-buildings":            ActionRepairDamagedBuildings,
	"recall-stray-units":         ActionRecallStrayUnits,
	"scout":                       ActionScoutWithIdleUnits,
	"send-harvesters":             ActionSendIdleHarvesters,
	"produce-engineer":            ActionProduceEngineer,
	"capture-building":            ActionCaptureBuilding,
	"produce-harvester":           ActionProduceHarvester,
	"attack-move-ground":          ActionAttackMoveIdleGroundUnits,
	"attack-known-base-ground":    ActionAttackKnownBaseGround,
	"air-attack-enemy":            ActionAirAttackEnemy,
	"air-attack-known-base":       ActionAirAttackKnownBase,
	"naval-attack-enemy":          ActionNavalAttackEnemy,
	"produce-missile-silo":        ActionProduceMissileSilo,
	"produce-iron-curtain":        ActionProduceIronCurtain,
	"fire-nuke":                   ActionFireNuke,
	"fire-iron-curtain":           ActionFireIronCurtain,
	"fire-spy-plane":              ActionFireSpyPlane,
	"fire-paratroopers":           ActionFireParatroopers,
	"fire-parabombs":              ActionFireParabombs,
	"produce-grenadier":           ActionProduceGrenadier,
	"produce-attack-dog":          ActionProduceAttackDog,
	"produce-spy":                 ActionProduceSpy,
	"produce-mad-tank":            ActionProduceMADTank,
	"produce-minelayer":           ActionProduceMinelayer,
	"produce-kennel":              ActionProduceKennel,
	"lay-mines":                   ActionLayMines,
	"produce-flame-tower":         ActionProduceFlameTower,
	"produce-tesla-coil":          ActionProduceTeslaCoil,

	// Used by compiled rules but missing until the vimyc port needed to name
	// them — nothing reads this map, which is how they went unnoticed.
	"cancel-stuck-aircraft":      ActionCancelStuckAircraft,
	"defend-critical-building":   ActionDefendCriticalBuilding,
	"deliver-assault-apc":        ActionDeliverAssaultAPC,
	"load-combat-infantry":       ActionLoadCombatInfantry,
	"load-engineer-into-apc":     ActionLoadEngineerIntoAPC,
	"naval-defend-base":          ActionNavalDefendBase,
	"produce-apc":                ActionProduceAPC,
	"produce-basic-aircraft":     ActionProduceBasicAircraft,
	"produce-flak-truck":         ActionProduceFlakTruck,
	"produce-gap-generator":      ActionProduceGapGenerator,
	"produce-gunboat":            ActionProduceGunboat,
	"produce-scout-vehicle":      ActionProduceScoutVehicle,
	"produce-siege-vehicle":      ActionProduceSiegeVehicle,
	"scout-patrol":               ActionScoutPatrol,
	"unblock-war-factory-egress": ActionUnblockWarFactoryEgress,
	"unload-apc-near-target":     ActionUnloadAPCNearTarget,
}
