package rules

// ActionRegistry maps action names to their implementations.
// The compiler references action functions directly, but the registry
// enables future serialization and introspection.
var ActionRegistry = map[string]ActionFunc{
	"produce_mcv":          ActionProduceMCV,
	"deploy_mcv":           ActionDeployMCV,
	"produce_power_plant":  ActionProducePowerPlant,
	"produce_refinery":     ActionProduceRefinery,
	"produce_barracks":     ActionProduceBarracks,
	"produce_war_factory":  ActionProduceWarFactory,
	"produce_radar":        ActionProduceRadar,
	"produce_airfield":     ActionProduceAirfield,
	"produce_naval_yard":     ActionProduceNavalYard,
	"produce_service_depot":  ActionProduceServiceDepot,
	"place_building":       ActionPlaceBuilding,
	"produce_infantry":     ActionProduceInfantry,
	"produce_vehicle":      ActionProduceVehicle,
	"produce_aircraft":     ActionProduceAircraft,
	"produce_ship":         ActionProduceShip,
	"place_defense":            ActionPlaceDefense,
	"produce_defense":          ActionProduceDefense,
	"produce_aa_defense":       ActionProduceAADefense,
	"produce_tech_center":      ActionProduceTechCenter,
	"produce_heavy_vehicle":    ActionProduceHeavyVehicle,
	"produce_rocket_soldier":        ActionProduceRocketSoldier,
	"produce_specialist_infantry":   ActionProduceSpecialistInfantry,
	"produce_advanced_aircraft": ActionProduceAdvancedAircraft,
	"produce_advanced_power":   ActionProduceAdvancedPower,
	"produce_ore_silo":         ActionProduceOreSilo,
	"produce_advanced_ship":    ActionProduceAdvancedShip,
	"defend_base":              ActionDefendBase,
	"air_defend_base":          ActionAirDefendBase,
	"repair_buildings":     ActionRepairDamagedBuildings,
	"scout":                ActionScoutWithIdleUnits,
	"send_harvesters":      ActionSendIdleHarvesters,
	"produce_engineer":     ActionProduceEngineer,
	"capture_building":     ActionCaptureBuilding,
	"produce_harvester":          ActionProduceHarvester,
	"attack_move_ground":         ActionAttackMoveIdleGroundUnits,
	"attack_known_base_ground":   ActionAttackKnownBaseGround,
	"air_attack_enemy":           ActionAirAttackEnemy,
	"air_attack_known_base":      ActionAirAttackKnownBase,
	"naval_attack_enemy":         ActionNavalAttackEnemy,
}
