package rules

// DefaultRules returns the seed rule set for autonomous play.
func DefaultRules() []*Rule {
	return []*Rule{
		{
			Name:         "deploy-mcv",
			Priority:     1000,
			Category:     "setup",
			Exclusive:    true,
			ConditionSrc: `HasUnit("mcv") && !HasBuilding("fact")`,
			Action:       ActionDeployMCV,
		},
		{
			Name:         "place-ready-building",
			Priority:     900,
			Category:     "economy",
			Exclusive:    true,
			ConditionSrc: `QueueReady("Building")`,
			Action:       ActionPlaceBuilding,
		},
		{
			Name:         "build-power",
			Priority:     800,
			Category:     "economy",
			Exclusive:    true,
			ConditionSrc: `!QueueBusy("Building") && CanBuild("Building","powr") && (PowerExcess() < 100 || BuildingCount("powr") == 0) && Cash() >= 300`,
			Action:       ActionProducePowerPlant,
		},
		{
			Name:         "build-refinery",
			Priority:     750,
			Category:     "economy",
			Exclusive:    true,
			ConditionSrc: `!QueueBusy("Building") && CanBuild("Building","proc") && !HasBuilding("proc") && Cash() >= 2000`,
			Action:       ActionProduceRefinery,
		},
		{
			Name:         "build-barracks",
			Priority:     700,
			Category:     "economy",
			Exclusive:    true,
			ConditionSrc: `!QueueBusy("Building") && CanBuildRole("barracks") && !HasRole("barracks") && PowerExcess() >= 0 && Cash() >= 300`,
			Action:       ActionProduceBarracks,
		},
		{
			Name:         "build-war-factory",
			Priority:     650,
			Category:     "economy",
			Exclusive:    true,
			ConditionSrc: `!QueueBusy("Building") && CanBuild("Building","weap") && !HasBuilding("weap") && PowerExcess() >= 0 && Cash() >= 2000`,
			Action:       ActionProduceWarFactory,
		},
		{
			Name:         "produce-infantry",
			Priority:     500,
			Category:     "production",
			Exclusive:    false,
			ConditionSrc: `HasRole("barracks") && !QueueBusy("Infantry") && UnitCount("e1") < 10 && Cash() >= 100`,
			Action:       ActionProduceInfantry,
		},
		{
			Name:         "defend-base",
			Priority:     400,
			Category:     "combat",
			Exclusive:    false,
			ConditionSrc: `BaseUnderAttack() && len(IdleGroundUnits()) >= 2`,
			Action:       ActionDefendBase,
		},
		{
			Name:         "scout-with-idle-units",
			Priority:     350,
			Category:     "recon",
			Exclusive:    false,
			ConditionSrc: `!EnemiesVisible() && !HasEnemyIntel() && len(IdleGroundUnits()) >= 5`,
			Action:       ActionScoutWithIdleUnits,
		},
		{
			Name:         "attack-idle-units",
			Priority:     300,
			Category:     "combat",
			Exclusive:    false,
			ConditionSrc: `len(IdleGroundUnits()) >= 5 && NearestEnemy() != nil`,
			Action:       ActionAttackMoveIdleGroundUnits,
		},
		{
			Name:         "attack-known-base",
			Priority:     290,
			Category:     "combat",
			Exclusive:    false,
			ConditionSrc: `!EnemiesVisible() && HasEnemyIntel() && len(IdleGroundUnits()) >= 5`,
			Action:       ActionAttackKnownBaseGround,
		},
		{
			Name:         "repair-buildings",
			Priority:     200,
			Category:     "maintenance",
			Exclusive:    false,
			ConditionSrc: `len(DamagedBuildings()) > 0`,
			Action:       ActionRepairDamagedBuildings,
		},
		{
			Name:         "return-idle-harvesters",
			Priority:     100,
			Category:     "harvester",
			Exclusive:    false,
			ConditionSrc: `len(IdleHarvesters()) > 0`,
			Action:       ActionSendIdleHarvesters,
		},
	}
}
