// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Insight struct {
	GameID      int64  `json:"game_id"`
	Rules       string `json:"rules"`
	CreatedAt   int64  `json:"created_at"`
	Summary     string `json:"summary"`
	Suggestion  string `json:"suggestion"`
	InsightJson string `json:"insight_json"`
}
