// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
)

const dropInsight = `-- name: DropInsight :exec
DELETE FROM insights WHERE game_id = ? AND rules = ?
`

type DropInsightParams struct {
	GameID int64  `json:"game_id"`
	Rules  string `json:"rules"`
}

func (q *Queries) DropInsight(ctx context.Context, arg DropInsightParams) error {
	_, err := q.db.ExecContext(ctx, dropInsight, arg.GameID, arg.Rules)
	return err
}

const getInsight = `-- name: GetInsight :one
SELECT insight_json FROM insights
WHERE game_id = ? AND rules = ?
`

type GetInsightParams struct {
	GameID int64  `json:"game_id"`
	Rules  string `json:"rules"`
}

func (q *Queries) GetInsight(ctx context.Context, arg GetInsightParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getInsight, arg.GameID, arg.Rules)
	var insight_json string
	err := row.Scan(&insight_json)
	return insight_json, err
}

const listInsights = `-- name: ListInsights :many
SELECT game_id, summary, suggestion, created_at FROM insights
WHERE rules = ?
ORDER BY created_at DESC
`

type ListInsightsRow struct {
	GameID     int64  `json:"game_id"`
	Summary    string `json:"summary"`
	Suggestion string `json:"suggestion"`
	CreatedAt  int64  `json:"created_at"`
}

// Every reading made against one rule set, newest first. What the cross-game
// work reads.
func (q *Queries) ListInsights(ctx context.Context, rules string) ([]ListInsightsRow, error) {
	rows, err := q.db.QueryContext(ctx, listInsights, rules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInsightsRow
	for rows.Next() {
		var i ListInsightsRow
		if err := rows.Scan(
			&i.GameID,
			&i.Summary,
			&i.Suggestion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putInsight = `-- name: PutInsight :exec
INSERT INTO insights (game_id, rules, created_at, summary, suggestion, insight_json)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (game_id, rules) DO UPDATE SET
    created_at   = excluded.created_at,
    summary      = excluded.summary,
    suggestion   = excluded.suggestion,
    insight_json = excluded.insight_json
`

type PutInsightParams struct {
	GameID      int64  `json:"game_id"`
	Rules       string `json:"rules"`
	CreatedAt   int64  `json:"created_at"`
	Summary     string `json:"summary"`
	Suggestion  string `json:"suggestion"`
	InsightJson string `json:"insight_json"`
}

func (q *Queries) PutInsight(ctx context.Context, arg PutInsightParams) error {
	_, err := q.db.ExecContext(ctx, putInsight,
		arg.GameID,
		arg.Rules,
		arg.CreatedAt,
		arg.Summary,
		arg.Suggestion,
		arg.InsightJson,
	)
	return err
}
