// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	DropInsight(ctx context.Context, arg DropInsightParams) error
	GetInsight(ctx context.Context, arg GetInsightParams) (string, error)
	// Every reading made against one rule set, newest first. What the cross-game
	// work reads.
	ListInsights(ctx context.Context, rules string) ([]ListInsightsRow, error)
	PutInsight(ctx context.Context, arg PutInsightParams) error
}

var _ Querier = (*Queries)(nil)
