// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type ArchivedDoctrine struct {
	ID           int64          `json:"id"`
	GameID       int64          `json:"game_id"`
	Tick         int64          `json:"tick"`
	DoctrineJson string         `json:"doctrine_json"`
	Rating       sql.NullString `json:"rating"`
	RatingReason sql.NullString `json:"rating_reason"`
	RuleSetJson  sql.NullString `json:"rule_set_json"`
}

type Game struct {
	ID                       int64           `json:"id"`
	PlayedAt                 int64           `json:"played_at"`
	OurFaction               string          `json:"our_faction"`
	OpponentFaction          sql.NullString  `json:"opponent_faction"`
	MapWidth                 int64           `json:"map_width"`
	MapHeight                int64           `json:"map_height"`
	DurationTicks            int64           `json:"duration_ticks"`
	Won                      int64           `json:"won"`
	QualityTag               sql.NullString  `json:"quality_tag"`
	ReviewJson               sql.NullString  `json:"review_json"`
	ExportPath               sql.NullString  `json:"export_path"`
	Directive                sql.NullString  `json:"directive"`
	EnemyUnitsKilled         sql.NullInt64   `json:"enemy_units_killed"`
	EnemyBuildingsKilled     sql.NullInt64   `json:"enemy_buildings_killed"`
	EnemyUnitsPresumed       sql.NullInt64   `json:"enemy_units_presumed"`
	InfantryLost             sql.NullInt64   `json:"infantry_lost"`
	VehiclesLost             sql.NullInt64   `json:"vehicles_lost"`
	InfantryLostForward      sql.NullInt64   `json:"infantry_lost_forward"`
	VehiclesLostForward      sql.NullInt64   `json:"vehicles_lost_forward"`
	EngineUnitsKilled        sql.NullInt64   `json:"engine_units_killed"`
	EngineUnitsDead          sql.NullInt64   `json:"engine_units_dead"`
	EngineBuildingsKilled    sql.NullInt64   `json:"engine_buildings_killed"`
	EngineBuildingsDead      sql.NullInt64   `json:"engine_buildings_dead"`
	EngineKillsCost          sql.NullInt64   `json:"engine_kills_cost"`
	EngineDeathsCost         sql.NullInt64   `json:"engine_deaths_cost"`
	EngineArmyValue          sql.NullInt64   `json:"engine_army_value"`
	EngineEarned             sql.NullInt64   `json:"engine_earned"`
	OurArmyPeak              sql.NullInt64   `json:"our_army_peak"`
	OurArmyMean              sql.NullInt64   `json:"our_army_mean"`
	EnemyArmySeenPeak        sql.NullInt64   `json:"enemy_army_seen_peak"`
	EnemyArmySeenMean        sql.NullInt64   `json:"enemy_army_seen_mean"`
	HarvesterIdle            sql.NullInt64   `json:"harvester_idle"`
	HarvesterMining          sql.NullInt64   `json:"harvester_mining"`
	HarvesterTravelling      sql.NullInt64   `json:"harvester_travelling"`
	HarvesterAtRefinery      sql.NullInt64   `json:"harvester_at_refinery"`
	HarvesterHaulDistance    sql.NullFloat64 `json:"harvester_haul_distance"`
	StrikeBlockedUnclumped   sql.NullInt64   `json:"strike_blocked_unclumped"`
	StrikeBlockedNoTarget    sql.NullInt64   `json:"strike_blocked_no_target"`
	StrikeBlockedNotBuilding sql.NullInt64   `json:"strike_blocked_not_building"`
	StrikeBlockedOutOfReach  sql.NullInt64   `json:"strike_blocked_out_of_reach"`
	StrikeBlockedBlindAtBase sql.NullInt64   `json:"strike_blocked_blind_at_base"`
	StrikeBlockedEnRoute     sql.NullInt64   `json:"strike_blocked_en_route"`
}

type Lesson struct {
	ID             int64          `json:"id"`
	GameID         int64          `json:"game_id"`
	CreatedAt      int64          `json:"created_at"`
	TriggerText    string         `json:"trigger_text"`
	GuidanceText   string         `json:"guidance_text"`
	Confidence     float64        `json:"confidence"`
	AppliesFaction string         `json:"applies_faction"`
	AppliesVs      sql.NullString `json:"applies_vs"`
}

type RuleFiring struct {
	ID         int64         `json:"id"`
	DoctrineID int64         `json:"doctrine_id"`
	RuleName   string        `json:"rule_name"`
	FireCount  int64         `json:"fire_count"`
	FirstTick  int64         `json:"first_tick"`
	LastTick   int64         `json:"last_tick"`
	ActCount   sql.NullInt64 `json:"act_count"`
}
