// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countLosses = `-- name: CountLosses :one
SELECT COUNT(*) FROM games WHERE won = 0
`

func (q *Queries) CountLosses(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLosses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWins = `-- name: CountWins :one
SELECT COUNT(*) FROM games WHERE won = 1
`

func (q *Queries) CountWins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGame = `-- name: GetGame :one
SELECT id, played_at, our_faction, opponent_faction,
       map_width, map_height, duration_ticks, won,
       quality_tag, review_json
FROM games WHERE id = ?
`

func (q *Queries) GetGame(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlayedAt,
		&i.OurFaction,
		&i.OpponentFaction,
		&i.MapWidth,
		&i.MapHeight,
		&i.DurationTicks,
		&i.Won,
		&i.QualityTag,
		&i.ReviewJson,
	)
	return i, err
}

const insertDoctrine = `-- name: InsertDoctrine :one
INSERT INTO archived_doctrines (
    game_id, tick, doctrine_json, rating, rating_reason, rule_set_json
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertDoctrineParams struct {
	GameID       int64          `json:"game_id"`
	Tick         int64          `json:"tick"`
	DoctrineJson string         `json:"doctrine_json"`
	Rating       sql.NullString `json:"rating"`
	RatingReason sql.NullString `json:"rating_reason"`
	RuleSetJson  sql.NullString `json:"rule_set_json"`
}

func (q *Queries) InsertDoctrine(ctx context.Context, arg InsertDoctrineParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDoctrine,
		arg.GameID,
		arg.Tick,
		arg.DoctrineJson,
		arg.Rating,
		arg.RatingReason,
		arg.RuleSetJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertGame = `-- name: InsertGame :one
INSERT INTO games (
    played_at, our_faction, opponent_faction,
    map_width, map_height, duration_ticks,
    won, quality_tag, review_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertGameParams struct {
	PlayedAt        int64          `json:"played_at"`
	OurFaction      string         `json:"our_faction"`
	OpponentFaction sql.NullString `json:"opponent_faction"`
	MapWidth        int64          `json:"map_width"`
	MapHeight       int64          `json:"map_height"`
	DurationTicks   int64          `json:"duration_ticks"`
	Won             int64          `json:"won"`
	QualityTag      sql.NullString `json:"quality_tag"`
	ReviewJson      sql.NullString `json:"review_json"`
}

func (q *Queries) InsertGame(ctx context.Context, arg InsertGameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertGame,
		arg.PlayedAt,
		arg.OurFaction,
		arg.OpponentFaction,
		arg.MapWidth,
		arg.MapHeight,
		arg.DurationTicks,
		arg.Won,
		arg.QualityTag,
		arg.ReviewJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLesson = `-- name: InsertLesson :exec
INSERT INTO lessons (
    game_id, created_at, trigger_text, guidance_text,
    confidence, applies_faction, applies_vs
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertLessonParams struct {
	GameID         int64          `json:"game_id"`
	CreatedAt      int64          `json:"created_at"`
	TriggerText    string         `json:"trigger_text"`
	GuidanceText   string         `json:"guidance_text"`
	Confidence     float64        `json:"confidence"`
	AppliesFaction string         `json:"applies_faction"`
	AppliesVs      sql.NullString `json:"applies_vs"`
}

func (q *Queries) InsertLesson(ctx context.Context, arg InsertLessonParams) error {
	_, err := q.db.ExecContext(ctx, insertLesson,
		arg.GameID,
		arg.CreatedAt,
		arg.TriggerText,
		arg.GuidanceText,
		arg.Confidence,
		arg.AppliesFaction,
		arg.AppliesVs,
	)
	return err
}

const insertRuleFiring = `-- name: InsertRuleFiring :exec
INSERT INTO rule_firings (
    doctrine_id, rule_name, fire_count, first_tick, last_tick
) VALUES (?, ?, ?, ?, ?)
`

type InsertRuleFiringParams struct {
	DoctrineID int64  `json:"doctrine_id"`
	RuleName   string `json:"rule_name"`
	FireCount  int64  `json:"fire_count"`
	FirstTick  int64  `json:"first_tick"`
	LastTick   int64  `json:"last_tick"`
}

func (q *Queries) InsertRuleFiring(ctx context.Context, arg InsertRuleFiringParams) error {
	_, err := q.db.ExecContext(ctx, insertRuleFiring,
		arg.DoctrineID,
		arg.RuleName,
		arg.FireCount,
		arg.FirstTick,
		arg.LastTick,
	)
	return err
}

const listGames = `-- name: ListGames :many
SELECT our_faction, won FROM games ORDER BY played_at ASC
`

type ListGamesRow struct {
	OurFaction string `json:"our_faction"`
	Won        int64  `json:"won"`
}

func (q *Queries) ListGames(ctx context.Context) ([]ListGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGamesRow
	for rows.Next() {
		var i ListGamesRow
		if err := rows.Scan(&i.OurFaction, &i.Won); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesDetailed = `-- name: ListGamesDetailed :many
SELECT id, played_at, our_faction, opponent_faction,
       map_width, map_height, duration_ticks, won,
       quality_tag, review_json
FROM games
ORDER BY played_at DESC
LIMIT ? OFFSET ?
`

type ListGamesDetailedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListGamesDetailed(ctx context.Context, arg ListGamesDetailedParams) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, listGamesDetailed, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.PlayedAt,
			&i.OurFaction,
			&i.OpponentFaction,
			&i.MapWidth,
			&i.MapHeight,
			&i.DurationTicks,
			&i.Won,
			&i.QualityTag,
			&i.ReviewJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLessons = `-- name: ListTopLessons :many
SELECT trigger_text, guidance_text, confidence,
       applies_faction, applies_vs
FROM lessons
ORDER BY confidence DESC, created_at DESC
LIMIT ?
`

type ListTopLessonsRow struct {
	TriggerText    string         `json:"trigger_text"`
	GuidanceText   string         `json:"guidance_text"`
	Confidence     float64        `json:"confidence"`
	AppliesFaction string         `json:"applies_faction"`
	AppliesVs      sql.NullString `json:"applies_vs"`
}

func (q *Queries) ListTopLessons(ctx context.Context, limit int64) ([]ListTopLessonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopLessons, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopLessonsRow
	for rows.Next() {
		var i ListTopLessonsRow
		if err := rows.Scan(
			&i.TriggerText,
			&i.GuidanceText,
			&i.Confidence,
			&i.AppliesFaction,
			&i.AppliesVs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryCautionaryDoctrines = `-- name: QueryCautionaryDoctrines :many
SELECT d.doctrine_json, d.rating, d.rating_reason,
       g.won, g.quality_tag, g.opponent_faction, g.played_at
FROM archived_doctrines d
JOIN games g ON d.game_id = g.id
WHERE g.our_faction = ?1
  AND d.rating = 'weak'
ORDER BY g.played_at DESC
LIMIT ?2
`

type QueryCautionaryDoctrinesParams struct {
	OurFaction string `json:"our_faction"`
	Lim        int64  `json:"lim"`
}

type QueryCautionaryDoctrinesRow struct {
	DoctrineJson    string         `json:"doctrine_json"`
	Rating          sql.NullString `json:"rating"`
	RatingReason    sql.NullString `json:"rating_reason"`
	Won             int64          `json:"won"`
	QualityTag      sql.NullString `json:"quality_tag"`
	OpponentFaction sql.NullString `json:"opponent_faction"`
	PlayedAt        int64          `json:"played_at"`
}

// Opponent faction is NOT filtered here; the librarian decides whether the
// failure mode transfers across opponents.
func (q *Queries) QueryCautionaryDoctrines(ctx context.Context, arg QueryCautionaryDoctrinesParams) ([]QueryCautionaryDoctrinesRow, error) {
	rows, err := q.db.QueryContext(ctx, queryCautionaryDoctrines, arg.OurFaction, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryCautionaryDoctrinesRow
	for rows.Next() {
		var i QueryCautionaryDoctrinesRow
		if err := rows.Scan(
			&i.DoctrineJson,
			&i.Rating,
			&i.RatingReason,
			&i.Won,
			&i.QualityTag,
			&i.OpponentFaction,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryExemplarDoctrines = `-- name: QueryExemplarDoctrines :many
SELECT d.doctrine_json, d.rating, d.rating_reason,
       g.won, g.quality_tag, g.opponent_faction, g.played_at
FROM archived_doctrines d
JOIN games g ON d.game_id = g.id
WHERE g.our_faction = ?1
  AND g.quality_tag = 'exemplary'
  AND d.rating IN ('strong', 'adequate')
ORDER BY g.played_at DESC
LIMIT ?2
`

type QueryExemplarDoctrinesParams struct {
	OurFaction string `json:"our_faction"`
	Lim        int64  `json:"lim"`
}

type QueryExemplarDoctrinesRow struct {
	DoctrineJson    string         `json:"doctrine_json"`
	Rating          sql.NullString `json:"rating"`
	RatingReason    sql.NullString `json:"rating_reason"`
	Won             int64          `json:"won"`
	QualityTag      sql.NullString `json:"quality_tag"`
	OpponentFaction sql.NullString `json:"opponent_faction"`
	PlayedAt        int64          `json:"played_at"`
}

// Opponent faction is NOT filtered here; the librarian judges cross-opponent
// relevance semantically. SQL only scopes to our faction + rating quality.
func (q *Queries) QueryExemplarDoctrines(ctx context.Context, arg QueryExemplarDoctrinesParams) ([]QueryExemplarDoctrinesRow, error) {
	rows, err := q.db.QueryContext(ctx, queryExemplarDoctrines, arg.OurFaction, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryExemplarDoctrinesRow
	for rows.Next() {
		var i QueryExemplarDoctrinesRow
		if err := rows.Scan(
			&i.DoctrineJson,
			&i.Rating,
			&i.RatingReason,
			&i.Won,
			&i.QualityTag,
			&i.OpponentFaction,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryLessons = `-- name: QueryLessons :many
SELECT trigger_text, guidance_text, confidence
FROM lessons
WHERE applies_faction = ?1
ORDER BY confidence DESC, created_at DESC
LIMIT ?2
`

type QueryLessonsParams struct {
	OurFaction string `json:"our_faction"`
	Lim        int64  `json:"lim"`
}

type QueryLessonsRow struct {
	TriggerText  string  `json:"trigger_text"`
	GuidanceText string  `json:"guidance_text"`
	Confidence   float64 `json:"confidence"`
}

// Opponent faction is NOT filtered here; lessons are often generalizable
// across opponents and the librarian will drop what doesn't apply.
func (q *Queries) QueryLessons(ctx context.Context, arg QueryLessonsParams) ([]QueryLessonsRow, error) {
	rows, err := q.db.QueryContext(ctx, queryLessons, arg.OurFaction, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryLessonsRow
	for rows.Next() {
		var i QueryLessonsRow
		if err := rows.Scan(&i.TriggerText, &i.GuidanceText, &i.Confidence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
