// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CountLosses(ctx context.Context) (int64, error)
	CountWins(ctx context.Context) (int64, error)
	GetGame(ctx context.Context, id int64) (GetGameRow, error)
	GetGameOutcome(ctx context.Context, id int64) (GetGameOutcomeRow, error)
	InsertDoctrine(ctx context.Context, arg InsertDoctrineParams) (int64, error)
	InsertGame(ctx context.Context, arg InsertGameParams) (int64, error)
	InsertLesson(ctx context.Context, arg InsertLessonParams) error
	InsertRuleFiring(ctx context.Context, arg InsertRuleFiringParams) error
	ListAllGames(ctx context.Context) ([]ListAllGamesRow, error)
	// Every doctrine window of one game, in the order they took effect.
	ListDoctrinesForGame(ctx context.Context, gameID int64) ([]ListDoctrinesForGameRow, error)
	// What each rule actually did during the game, summed over its doctrine
	// windows. act_count is NULL for games recorded before it was measured.
	ListFiringsForGame(ctx context.Context, gameID int64) ([]ListFiringsForGameRow, error)
	ListGames(ctx context.Context) ([]ListGamesRow, error)
	ListGamesDetailed(ctx context.Context, arg ListGamesDetailedParams) ([]ListGamesDetailedRow, error)
	// Games with a recorded state export, newest first: the ones Currie can replay.
	ListReplayableGames(ctx context.Context) ([]ListReplayableGamesRow, error)
	ListTopLessons(ctx context.Context, limit int64) ([]ListTopLessonsRow, error)
	// Opponent faction is NOT filtered here; the librarian decides whether the
	// failure mode transfers across opponents.
	QueryCautionaryDoctrines(ctx context.Context, arg QueryCautionaryDoctrinesParams) ([]QueryCautionaryDoctrinesRow, error)
	// Opponent faction is NOT filtered here; the librarian judges cross-opponent
	// relevance semantically. SQL only scopes to our faction + rating quality.
	//
	// Gated on the per-doctrine rating, not on the game quality_tag, because that
	// tag requires won=true and this bot has never won. 158 games, every one tagged
	// cautionary or mixed, so this query returned nothing for its entire history
	// while its cautionary counterpart accumulated 1276 patterns. The library could
	// only ever say what to avoid.
	//
	// The asymmetry was structural: cautionary passes one gate, the doctrine rating
	// alone, and this passed two, the second unreachable. Both now trust the same
	// signal. Game 141 - 226600 ticks, 19 buildings destroyed, a 0.98 trade, the
	// best game on record - contributed 6 failure patterns and 0 successes, because
	// it was a loss. Its 20 strong and adequate doctrines become visible here.
	//
	// Only TopKExemplars rows reach the librarian - two - so this ORDER BY decides
	// what the strategist ever sees, and recency is the wrong tiebreak. Ordered by
	// recency it returned two doctrines from game 169, which ran 25790 ticks and
	// destroyed nothing, ahead of game 141. So rank by what the game achieved:
	// genuinely exemplary first, then strong over adequate, then buildings
	// destroyed, then recency. Buildings destroyed is the measure that correlates
	// with every other outcome in 32 games and is the only one about winning.
	//
	// A doctrine rated strong inside a lost game is still weaker evidence than one
	// from a win. The context line carries the result, so the librarian and the
	// strategist both see that the game was lost.
	QueryExemplarDoctrines(ctx context.Context, arg QueryExemplarDoctrinesParams) ([]QueryExemplarDoctrinesRow, error)
	// Opponent faction is NOT filtered here; lessons are often generalizable
	// across opponents and the librarian will drop what doesn't apply.
	QueryLessons(ctx context.Context, arg QueryLessonsParams) ([]QueryLessonsRow, error)
	// Backfill: associate an export with a game recorded before provenance existed.
	SetGameExportPath(ctx context.Context, arg SetGameExportPathParams) error
}

var _ Querier = (*Queries)(nil)
