#!/bin/sh
# Generates the token tables the syntax highlighting is built from, so adding a
# keyword or an operator to the language needs no edit here. Run by `make rules`.
set -e
vimyc="$1"
out="$2"
{
	printf '// Code generated by gen_tokens.sh from `vimyc --tokens`. DO NOT EDIT.\n\n'
	printf 'package views\n\nimport "strings"\n\n'
	printf '// The language'"'"'s vocabulary, from the compiler'"'"'s own tables.\n'
	printf '//\n'
	printf '// Operators are longest-first, which both consumers need: a lexer must try\n'
	printf '// `<=` before `<`, and so must a regex alternation.\n'
	printf 'var (\n'
	"$vimyc" --tokens | while read -r kind rest; do
		case "$kind" in
		keyword) name="vyKeywords" ;;
		operator) name="vyOperators" ;;
		punctuation) name="vyPunctuation" ;;
		*) continue ;;
		esac
		printf '\t%s = strings.Fields("%s")\n' "$name" "$rest"
	done
	printf ')\n'
} > "$out.tmp"
mv "$out.tmp" "$out"
