// Code generated by gen_tokens.sh from `vimyc --tokens`. DO NOT EDIT.

package views

import "strings"

// The language's vocabulary, from the compiler's own tables.
//
// Operators are longest-first, which both consumers need: a lexer must try
// `<=` before `<`, and so must a regex alternation.
var (
	vyKeywords    = strings.Fields("rule priority category exclusive do require because let and or not exists param def int float")
	vyOperators   = strings.Fields("<= >= == != < > + - * / =")
	vyPunctuation = strings.Fields("{ } ( ) , :")
)
